/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateOrUpdatePropertyFiscalYearRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdatePropertyFiscalYearRequest{}

// CreateOrUpdatePropertyFiscalYearRequest Request used to create or update a fiscal year period for a property.
type CreateOrUpdatePropertyFiscalYearRequest struct {
	// Start timestamp of the fiscal year (inclusive, epoch seconds)
	StartDate int64 `json:"start_date"`
	// End timestamp of the fiscal year (inclusive, epoch seconds)
	EndDate int64 `json:"end_date"`
}

type _CreateOrUpdatePropertyFiscalYearRequest CreateOrUpdatePropertyFiscalYearRequest

// NewCreateOrUpdatePropertyFiscalYearRequest instantiates a new CreateOrUpdatePropertyFiscalYearRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdatePropertyFiscalYearRequest(startDate int64, endDate int64) *CreateOrUpdatePropertyFiscalYearRequest {
	this := CreateOrUpdatePropertyFiscalYearRequest{}
	this.StartDate = startDate
	this.EndDate = endDate
	return &this
}

// NewCreateOrUpdatePropertyFiscalYearRequestWithDefaults instantiates a new CreateOrUpdatePropertyFiscalYearRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdatePropertyFiscalYearRequestWithDefaults() *CreateOrUpdatePropertyFiscalYearRequest {
	this := CreateOrUpdatePropertyFiscalYearRequest{}
	return &this
}

// GetStartDate returns the StartDate field value
func (o *CreateOrUpdatePropertyFiscalYearRequest) GetStartDate() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdatePropertyFiscalYearRequest) GetStartDateOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartDate, true
}

// SetStartDate sets field value
func (o *CreateOrUpdatePropertyFiscalYearRequest) SetStartDate(v int64) {
	o.StartDate = v
}

// GetEndDate returns the EndDate field value
func (o *CreateOrUpdatePropertyFiscalYearRequest) GetEndDate() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdatePropertyFiscalYearRequest) GetEndDateOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndDate, true
}

// SetEndDate sets field value
func (o *CreateOrUpdatePropertyFiscalYearRequest) SetEndDate(v int64) {
	o.EndDate = v
}

func (o CreateOrUpdatePropertyFiscalYearRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdatePropertyFiscalYearRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["start_date"] = o.StartDate
	toSerialize["end_date"] = o.EndDate
	return toSerialize, nil
}

func (o *CreateOrUpdatePropertyFiscalYearRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"start_date",
		"end_date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrUpdatePropertyFiscalYearRequest := _CreateOrUpdatePropertyFiscalYearRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrUpdatePropertyFiscalYearRequest)

	if err != nil {
		return err
	}

	*o = CreateOrUpdatePropertyFiscalYearRequest(varCreateOrUpdatePropertyFiscalYearRequest)

	return err
}

type NullableCreateOrUpdatePropertyFiscalYearRequest struct {
	value *CreateOrUpdatePropertyFiscalYearRequest
	isSet bool
}

func (v NullableCreateOrUpdatePropertyFiscalYearRequest) Get() *CreateOrUpdatePropertyFiscalYearRequest {
	return v.value
}

func (v *NullableCreateOrUpdatePropertyFiscalYearRequest) Set(val *CreateOrUpdatePropertyFiscalYearRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdatePropertyFiscalYearRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdatePropertyFiscalYearRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdatePropertyFiscalYearRequest(val *CreateOrUpdatePropertyFiscalYearRequest) *NullableCreateOrUpdatePropertyFiscalYearRequest {
	return &NullableCreateOrUpdatePropertyFiscalYearRequest{value: val, isSet: true}
}

func (v NullableCreateOrUpdatePropertyFiscalYearRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdatePropertyFiscalYearRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
