/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the QueryAppointmentSchedulesV2Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryAppointmentSchedulesV2Response{}

// QueryAppointmentSchedulesV2Response A page of the appointment schedules that match the query request
type QueryAppointmentSchedulesV2Response struct {
	Schedules []AppointmentSchedule `json:"schedules,omitempty"`
	// total number of schedules matching the query, ignoring limit and offset
	TotalCount *int64 `json:"total_count,omitempty"`
	// number of schedules that were skipped in the result
	Offset *int32 `json:"offset,omitempty"`
}

// NewQueryAppointmentSchedulesV2Response instantiates a new QueryAppointmentSchedulesV2Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryAppointmentSchedulesV2Response() *QueryAppointmentSchedulesV2Response {
	this := QueryAppointmentSchedulesV2Response{}
	return &this
}

// NewQueryAppointmentSchedulesV2ResponseWithDefaults instantiates a new QueryAppointmentSchedulesV2Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryAppointmentSchedulesV2ResponseWithDefaults() *QueryAppointmentSchedulesV2Response {
	this := QueryAppointmentSchedulesV2Response{}
	return &this
}

// GetSchedules returns the Schedules field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Response) GetSchedules() []AppointmentSchedule {
	if o == nil || IsNil(o.Schedules) {
		var ret []AppointmentSchedule
		return ret
	}
	return o.Schedules
}

// GetSchedulesOk returns a tuple with the Schedules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Response) GetSchedulesOk() ([]AppointmentSchedule, bool) {
	if o == nil || IsNil(o.Schedules) {
		return nil, false
	}
	return o.Schedules, true
}

// HasSchedules returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Response) HasSchedules() bool {
	if o != nil && !IsNil(o.Schedules) {
		return true
	}

	return false
}

// SetSchedules gets a reference to the given []AppointmentSchedule and assigns it to the Schedules field.
func (o *QueryAppointmentSchedulesV2Response) SetSchedules(v []AppointmentSchedule) {
	o.Schedules = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Response) GetTotalCount() int64 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int64
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Response) GetTotalCountOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Response) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *QueryAppointmentSchedulesV2Response) SetTotalCount(v int64) {
	o.TotalCount = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Response) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Response) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Response) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *QueryAppointmentSchedulesV2Response) SetOffset(v int32) {
	o.Offset = &v
}

func (o QueryAppointmentSchedulesV2Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryAppointmentSchedulesV2Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schedules) {
		toSerialize["schedules"] = o.Schedules
	}
	if !IsNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	return toSerialize, nil
}

type NullableQueryAppointmentSchedulesV2Response struct {
	value *QueryAppointmentSchedulesV2Response
	isSet bool
}

func (v NullableQueryAppointmentSchedulesV2Response) Get() *QueryAppointmentSchedulesV2Response {
	return v.value
}

func (v *NullableQueryAppointmentSchedulesV2Response) Set(val *QueryAppointmentSchedulesV2Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryAppointmentSchedulesV2Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryAppointmentSchedulesV2Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryAppointmentSchedulesV2Response(val *QueryAppointmentSchedulesV2Response) *NullableQueryAppointmentSchedulesV2Response {
	return &NullableQueryAppointmentSchedulesV2Response{value: val, isSet: true}
}

func (v NullableQueryAppointmentSchedulesV2Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryAppointmentSchedulesV2Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
