/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the GenerateCaseReportingEndpointNoticeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateCaseReportingEndpointNoticeRequest{}

// GenerateCaseReportingEndpointNoticeRequest struct for GenerateCaseReportingEndpointNoticeRequest
type GenerateCaseReportingEndpointNoticeRequest struct {
	// The language in which the PDF should be generated
	Language *string `json:"language,omitempty"`
}

// NewGenerateCaseReportingEndpointNoticeRequest instantiates a new GenerateCaseReportingEndpointNoticeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateCaseReportingEndpointNoticeRequest() *GenerateCaseReportingEndpointNoticeRequest {
	this := GenerateCaseReportingEndpointNoticeRequest{}
	return &this
}

// NewGenerateCaseReportingEndpointNoticeRequestWithDefaults instantiates a new GenerateCaseReportingEndpointNoticeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateCaseReportingEndpointNoticeRequestWithDefaults() *GenerateCaseReportingEndpointNoticeRequest {
	this := GenerateCaseReportingEndpointNoticeRequest{}
	return &this
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *GenerateCaseReportingEndpointNoticeRequest) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateCaseReportingEndpointNoticeRequest) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *GenerateCaseReportingEndpointNoticeRequest) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *GenerateCaseReportingEndpointNoticeRequest) SetLanguage(v string) {
	o.Language = &v
}

func (o GenerateCaseReportingEndpointNoticeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateCaseReportingEndpointNoticeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	return toSerialize, nil
}

type NullableGenerateCaseReportingEndpointNoticeRequest struct {
	value *GenerateCaseReportingEndpointNoticeRequest
	isSet bool
}

func (v NullableGenerateCaseReportingEndpointNoticeRequest) Get() *GenerateCaseReportingEndpointNoticeRequest {
	return v.value
}

func (v *NullableGenerateCaseReportingEndpointNoticeRequest) Set(val *GenerateCaseReportingEndpointNoticeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateCaseReportingEndpointNoticeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateCaseReportingEndpointNoticeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateCaseReportingEndpointNoticeRequest(val *GenerateCaseReportingEndpointNoticeRequest) *NullableGenerateCaseReportingEndpointNoticeRequest {
	return &NullableGenerateCaseReportingEndpointNoticeRequest{value: val, isSet: true}
}

func (v NullableGenerateCaseReportingEndpointNoticeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateCaseReportingEndpointNoticeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
