/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the UploadInvoiceAttachmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadInvoiceAttachmentResponse{}

// UploadInvoiceAttachmentResponse struct for UploadInvoiceAttachmentResponse
type UploadInvoiceAttachmentResponse struct {
	Attachment      *Attachment      `json:"attachment,omitempty"`
	InvoiceAnalysis *InvoiceAnalysis `json:"invoice_analysis,omitempty"`
}

// NewUploadInvoiceAttachmentResponse instantiates a new UploadInvoiceAttachmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadInvoiceAttachmentResponse() *UploadInvoiceAttachmentResponse {
	this := UploadInvoiceAttachmentResponse{}
	return &this
}

// NewUploadInvoiceAttachmentResponseWithDefaults instantiates a new UploadInvoiceAttachmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadInvoiceAttachmentResponseWithDefaults() *UploadInvoiceAttachmentResponse {
	this := UploadInvoiceAttachmentResponse{}
	return &this
}

// GetAttachment returns the Attachment field value if set, zero value otherwise.
func (o *UploadInvoiceAttachmentResponse) GetAttachment() Attachment {
	if o == nil || IsNil(o.Attachment) {
		var ret Attachment
		return ret
	}
	return *o.Attachment
}

// GetAttachmentOk returns a tuple with the Attachment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInvoiceAttachmentResponse) GetAttachmentOk() (*Attachment, bool) {
	if o == nil || IsNil(o.Attachment) {
		return nil, false
	}
	return o.Attachment, true
}

// HasAttachment returns a boolean if a field has been set.
func (o *UploadInvoiceAttachmentResponse) HasAttachment() bool {
	if o != nil && !IsNil(o.Attachment) {
		return true
	}

	return false
}

// SetAttachment gets a reference to the given Attachment and assigns it to the Attachment field.
func (o *UploadInvoiceAttachmentResponse) SetAttachment(v Attachment) {
	o.Attachment = &v
}

// GetInvoiceAnalysis returns the InvoiceAnalysis field value if set, zero value otherwise.
func (o *UploadInvoiceAttachmentResponse) GetInvoiceAnalysis() InvoiceAnalysis {
	if o == nil || IsNil(o.InvoiceAnalysis) {
		var ret InvoiceAnalysis
		return ret
	}
	return *o.InvoiceAnalysis
}

// GetInvoiceAnalysisOk returns a tuple with the InvoiceAnalysis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInvoiceAttachmentResponse) GetInvoiceAnalysisOk() (*InvoiceAnalysis, bool) {
	if o == nil || IsNil(o.InvoiceAnalysis) {
		return nil, false
	}
	return o.InvoiceAnalysis, true
}

// HasInvoiceAnalysis returns a boolean if a field has been set.
func (o *UploadInvoiceAttachmentResponse) HasInvoiceAnalysis() bool {
	if o != nil && !IsNil(o.InvoiceAnalysis) {
		return true
	}

	return false
}

// SetInvoiceAnalysis gets a reference to the given InvoiceAnalysis and assigns it to the InvoiceAnalysis field.
func (o *UploadInvoiceAttachmentResponse) SetInvoiceAnalysis(v InvoiceAnalysis) {
	o.InvoiceAnalysis = &v
}

func (o UploadInvoiceAttachmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadInvoiceAttachmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attachment) {
		toSerialize["attachment"] = o.Attachment
	}
	if !IsNil(o.InvoiceAnalysis) {
		toSerialize["invoice_analysis"] = o.InvoiceAnalysis
	}
	return toSerialize, nil
}

type NullableUploadInvoiceAttachmentResponse struct {
	value *UploadInvoiceAttachmentResponse
	isSet bool
}

func (v NullableUploadInvoiceAttachmentResponse) Get() *UploadInvoiceAttachmentResponse {
	return v.value
}

func (v *NullableUploadInvoiceAttachmentResponse) Set(val *UploadInvoiceAttachmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadInvoiceAttachmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadInvoiceAttachmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadInvoiceAttachmentResponse(val *UploadInvoiceAttachmentResponse) *NullableUploadInvoiceAttachmentResponse {
	return &NullableUploadInvoiceAttachmentResponse{value: val, isSet: true}
}

func (v NullableUploadInvoiceAttachmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadInvoiceAttachmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
