/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateOrUpdateAllocationKeyOverrideRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdateAllocationKeyOverrideRequest{}

// CreateOrUpdateAllocationKeyOverrideRequest Create or update an allocation key override.
type CreateOrUpdateAllocationKeyOverrideRequest struct {
	// ID of the cost type this override applies to.
	CostTypeRef string `json:"cost_type_ref"`
	// ID of the property this override applies to.
	PropertyRef string `json:"property_ref"`
	// First day the override is valid (timestamp in milliseconds, only the calendar day counts).
	ValidFrom int64 `json:"valid_from"`
	// Optional last day the override is valid (inclusive). If omitted, the override is valid indefinitely. Overrides of the same cost type and unit must not overlap.
	ValidTo *int64 `json:"valid_to,omitempty"`
	// Optional ID of the specific unit (child property) within the property that this override applies to. If omitted, the override applies to the property as a whole.
	UnitRef *string `json:"unit_ref,omitempty"`
	// Optional allocation key to use instead of the default.
	AllocationKeyRef *string                        `json:"allocation_key_ref,omitempty"`
	Mode             *AllocationKeyOverrideModeEnum `json:"mode,omitempty"`
	// Mode `ABSOLUTE`: optional fixed amount (in cents) instead of any key. The amount is charged in full for every fiscal year the override is valid in.
	AbsoluteAmount *int64 `json:"absolute_amount,omitempty"`
	// Mode `RATIO`: the quantity of the unit, e.g. 5 of 15 bins.
	Quantity *float64 `json:"quantity,omitempty"`
	// Mode `RATIO`: the total quantity the unit's quantity relates to, e.g. 15 bins. The unit bears `quantity / total_quantity` of the cost type.
	TotalQuantity *float64 `json:"total_quantity,omitempty"`
}

type _CreateOrUpdateAllocationKeyOverrideRequest CreateOrUpdateAllocationKeyOverrideRequest

// NewCreateOrUpdateAllocationKeyOverrideRequest instantiates a new CreateOrUpdateAllocationKeyOverrideRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateAllocationKeyOverrideRequest(costTypeRef string, propertyRef string, validFrom int64) *CreateOrUpdateAllocationKeyOverrideRequest {
	this := CreateOrUpdateAllocationKeyOverrideRequest{}
	this.CostTypeRef = costTypeRef
	this.PropertyRef = propertyRef
	this.ValidFrom = validFrom
	return &this
}

// NewCreateOrUpdateAllocationKeyOverrideRequestWithDefaults instantiates a new CreateOrUpdateAllocationKeyOverrideRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateAllocationKeyOverrideRequestWithDefaults() *CreateOrUpdateAllocationKeyOverrideRequest {
	this := CreateOrUpdateAllocationKeyOverrideRequest{}
	return &this
}

// GetCostTypeRef returns the CostTypeRef field value
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetCostTypeRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CostTypeRef
}

// GetCostTypeRefOk returns a tuple with the CostTypeRef field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetCostTypeRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CostTypeRef, true
}

// SetCostTypeRef sets field value
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetCostTypeRef(v string) {
	o.CostTypeRef = v
}

// GetPropertyRef returns the PropertyRef field value
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetPropertyRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PropertyRef
}

// GetPropertyRefOk returns a tuple with the PropertyRef field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetPropertyRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PropertyRef, true
}

// SetPropertyRef sets field value
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetPropertyRef(v string) {
	o.PropertyRef = v
}

// GetValidFrom returns the ValidFrom field value
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetValidFrom() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ValidFrom
}

// GetValidFromOk returns a tuple with the ValidFrom field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetValidFromOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidFrom, true
}

// SetValidFrom sets field value
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetValidFrom(v int64) {
	o.ValidFrom = v
}

// GetValidTo returns the ValidTo field value if set, zero value otherwise.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetValidTo() int64 {
	if o == nil || IsNil(o.ValidTo) {
		var ret int64
		return ret
	}
	return *o.ValidTo
}

// GetValidToOk returns a tuple with the ValidTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetValidToOk() (*int64, bool) {
	if o == nil || IsNil(o.ValidTo) {
		return nil, false
	}
	return o.ValidTo, true
}

// HasValidTo returns a boolean if a field has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) HasValidTo() bool {
	if o != nil && !IsNil(o.ValidTo) {
		return true
	}

	return false
}

// SetValidTo gets a reference to the given int64 and assigns it to the ValidTo field.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetValidTo(v int64) {
	o.ValidTo = &v
}

// GetUnitRef returns the UnitRef field value if set, zero value otherwise.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetUnitRef() string {
	if o == nil || IsNil(o.UnitRef) {
		var ret string
		return ret
	}
	return *o.UnitRef
}

// GetUnitRefOk returns a tuple with the UnitRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetUnitRefOk() (*string, bool) {
	if o == nil || IsNil(o.UnitRef) {
		return nil, false
	}
	return o.UnitRef, true
}

// HasUnitRef returns a boolean if a field has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) HasUnitRef() bool {
	if o != nil && !IsNil(o.UnitRef) {
		return true
	}

	return false
}

// SetUnitRef gets a reference to the given string and assigns it to the UnitRef field.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetUnitRef(v string) {
	o.UnitRef = &v
}

// GetAllocationKeyRef returns the AllocationKeyRef field value if set, zero value otherwise.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetAllocationKeyRef() string {
	if o == nil || IsNil(o.AllocationKeyRef) {
		var ret string
		return ret
	}
	return *o.AllocationKeyRef
}

// GetAllocationKeyRefOk returns a tuple with the AllocationKeyRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetAllocationKeyRefOk() (*string, bool) {
	if o == nil || IsNil(o.AllocationKeyRef) {
		return nil, false
	}
	return o.AllocationKeyRef, true
}

// HasAllocationKeyRef returns a boolean if a field has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) HasAllocationKeyRef() bool {
	if o != nil && !IsNil(o.AllocationKeyRef) {
		return true
	}

	return false
}

// SetAllocationKeyRef gets a reference to the given string and assigns it to the AllocationKeyRef field.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetAllocationKeyRef(v string) {
	o.AllocationKeyRef = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetMode() AllocationKeyOverrideModeEnum {
	if o == nil || IsNil(o.Mode) {
		var ret AllocationKeyOverrideModeEnum
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetModeOk() (*AllocationKeyOverrideModeEnum, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given AllocationKeyOverrideModeEnum and assigns it to the Mode field.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetMode(v AllocationKeyOverrideModeEnum) {
	o.Mode = &v
}

// GetAbsoluteAmount returns the AbsoluteAmount field value if set, zero value otherwise.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetAbsoluteAmount() int64 {
	if o == nil || IsNil(o.AbsoluteAmount) {
		var ret int64
		return ret
	}
	return *o.AbsoluteAmount
}

// GetAbsoluteAmountOk returns a tuple with the AbsoluteAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetAbsoluteAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.AbsoluteAmount) {
		return nil, false
	}
	return o.AbsoluteAmount, true
}

// HasAbsoluteAmount returns a boolean if a field has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) HasAbsoluteAmount() bool {
	if o != nil && !IsNil(o.AbsoluteAmount) {
		return true
	}

	return false
}

// SetAbsoluteAmount gets a reference to the given int64 and assigns it to the AbsoluteAmount field.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetAbsoluteAmount(v int64) {
	o.AbsoluteAmount = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetQuantity() float64 {
	if o == nil || IsNil(o.Quantity) {
		var ret float64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float64 and assigns it to the Quantity field.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetQuantity(v float64) {
	o.Quantity = &v
}

// GetTotalQuantity returns the TotalQuantity field value if set, zero value otherwise.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetTotalQuantity() float64 {
	if o == nil || IsNil(o.TotalQuantity) {
		var ret float64
		return ret
	}
	return *o.TotalQuantity
}

// GetTotalQuantityOk returns a tuple with the TotalQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) GetTotalQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalQuantity) {
		return nil, false
	}
	return o.TotalQuantity, true
}

// HasTotalQuantity returns a boolean if a field has been set.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) HasTotalQuantity() bool {
	if o != nil && !IsNil(o.TotalQuantity) {
		return true
	}

	return false
}

// SetTotalQuantity gets a reference to the given float64 and assigns it to the TotalQuantity field.
func (o *CreateOrUpdateAllocationKeyOverrideRequest) SetTotalQuantity(v float64) {
	o.TotalQuantity = &v
}

func (o CreateOrUpdateAllocationKeyOverrideRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdateAllocationKeyOverrideRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cost_type_ref"] = o.CostTypeRef
	toSerialize["property_ref"] = o.PropertyRef
	toSerialize["valid_from"] = o.ValidFrom
	if !IsNil(o.ValidTo) {
		toSerialize["valid_to"] = o.ValidTo
	}
	if !IsNil(o.UnitRef) {
		toSerialize["unit_ref"] = o.UnitRef
	}
	if !IsNil(o.AllocationKeyRef) {
		toSerialize["allocation_key_ref"] = o.AllocationKeyRef
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.AbsoluteAmount) {
		toSerialize["absolute_amount"] = o.AbsoluteAmount
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.TotalQuantity) {
		toSerialize["total_quantity"] = o.TotalQuantity
	}
	return toSerialize, nil
}

func (o *CreateOrUpdateAllocationKeyOverrideRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cost_type_ref",
		"property_ref",
		"valid_from",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrUpdateAllocationKeyOverrideRequest := _CreateOrUpdateAllocationKeyOverrideRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrUpdateAllocationKeyOverrideRequest)

	if err != nil {
		return err
	}

	*o = CreateOrUpdateAllocationKeyOverrideRequest(varCreateOrUpdateAllocationKeyOverrideRequest)

	return err
}

type NullableCreateOrUpdateAllocationKeyOverrideRequest struct {
	value *CreateOrUpdateAllocationKeyOverrideRequest
	isSet bool
}

func (v NullableCreateOrUpdateAllocationKeyOverrideRequest) Get() *CreateOrUpdateAllocationKeyOverrideRequest {
	return v.value
}

func (v *NullableCreateOrUpdateAllocationKeyOverrideRequest) Set(val *CreateOrUpdateAllocationKeyOverrideRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateAllocationKeyOverrideRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateAllocationKeyOverrideRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateAllocationKeyOverrideRequest(val *CreateOrUpdateAllocationKeyOverrideRequest) *NullableCreateOrUpdateAllocationKeyOverrideRequest {
	return &NullableCreateOrUpdateAllocationKeyOverrideRequest{value: val, isSet: true}
}

func (v NullableCreateOrUpdateAllocationKeyOverrideRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateAllocationKeyOverrideRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
