/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateAccountConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAccountConfigRequest{}

// UpdateAccountConfigRequest Request used to update the account configuration details
type UpdateAccountConfigRequest struct {
	AccountType      AccountTypeEnum           `json:"account_type"`
	ManagementConfig *PropertyManagementConfig `json:"management_config,omitempty"`
}

type _UpdateAccountConfigRequest UpdateAccountConfigRequest

// NewUpdateAccountConfigRequest instantiates a new UpdateAccountConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAccountConfigRequest(accountType AccountTypeEnum) *UpdateAccountConfigRequest {
	this := UpdateAccountConfigRequest{}
	this.AccountType = accountType
	return &this
}

// NewUpdateAccountConfigRequestWithDefaults instantiates a new UpdateAccountConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAccountConfigRequestWithDefaults() *UpdateAccountConfigRequest {
	this := UpdateAccountConfigRequest{}
	return &this
}

// GetAccountType returns the AccountType field value
func (o *UpdateAccountConfigRequest) GetAccountType() AccountTypeEnum {
	if o == nil {
		var ret AccountTypeEnum
		return ret
	}

	return o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value
// and a boolean to check if the value has been set.
func (o *UpdateAccountConfigRequest) GetAccountTypeOk() (*AccountTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountType, true
}

// SetAccountType sets field value
func (o *UpdateAccountConfigRequest) SetAccountType(v AccountTypeEnum) {
	o.AccountType = v
}

// GetManagementConfig returns the ManagementConfig field value if set, zero value otherwise.
func (o *UpdateAccountConfigRequest) GetManagementConfig() PropertyManagementConfig {
	if o == nil || IsNil(o.ManagementConfig) {
		var ret PropertyManagementConfig
		return ret
	}
	return *o.ManagementConfig
}

// GetManagementConfigOk returns a tuple with the ManagementConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAccountConfigRequest) GetManagementConfigOk() (*PropertyManagementConfig, bool) {
	if o == nil || IsNil(o.ManagementConfig) {
		return nil, false
	}
	return o.ManagementConfig, true
}

// HasManagementConfig returns a boolean if a field has been set.
func (o *UpdateAccountConfigRequest) HasManagementConfig() bool {
	if o != nil && !IsNil(o.ManagementConfig) {
		return true
	}

	return false
}

// SetManagementConfig gets a reference to the given PropertyManagementConfig and assigns it to the ManagementConfig field.
func (o *UpdateAccountConfigRequest) SetManagementConfig(v PropertyManagementConfig) {
	o.ManagementConfig = &v
}

func (o UpdateAccountConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAccountConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_type"] = o.AccountType
	if !IsNil(o.ManagementConfig) {
		toSerialize["management_config"] = o.ManagementConfig
	}
	return toSerialize, nil
}

func (o *UpdateAccountConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAccountConfigRequest := _UpdateAccountConfigRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateAccountConfigRequest)

	if err != nil {
		return err
	}

	*o = UpdateAccountConfigRequest(varUpdateAccountConfigRequest)

	return err
}

type NullableUpdateAccountConfigRequest struct {
	value *UpdateAccountConfigRequest
	isSet bool
}

func (v NullableUpdateAccountConfigRequest) Get() *UpdateAccountConfigRequest {
	return v.value
}

func (v *NullableUpdateAccountConfigRequest) Set(val *UpdateAccountConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAccountConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAccountConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAccountConfigRequest(val *UpdateAccountConfigRequest) *NullableUpdateAccountConfigRequest {
	return &NullableUpdateAccountConfigRequest{value: val, isSet: true}
}

func (v NullableUpdateAccountConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAccountConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
