/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// OutlookSenderTypeEnum The type of the email sender as resolved from the account's data.
type OutlookSenderTypeEnum string

// List of OutlookSenderTypeEnum
const (
	OUTLOOKSENDERTYPEENUM_TENANT   OutlookSenderTypeEnum = "tenant"
	OUTLOOKSENDERTYPEENUM_PROVIDER OutlookSenderTypeEnum = "provider"
	OUTLOOKSENDERTYPEENUM_UNKNOWN  OutlookSenderTypeEnum = "unknown"
)

// All allowed values of OutlookSenderTypeEnum enum
var AllowedOutlookSenderTypeEnumEnumValues = []OutlookSenderTypeEnum{
	"tenant",
	"provider",
	"unknown",
}

func (v *OutlookSenderTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OutlookSenderTypeEnum(value)
	for _, existing := range AllowedOutlookSenderTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OutlookSenderTypeEnum", value)
}

// NewOutlookSenderTypeEnumFromValue returns a pointer to a valid OutlookSenderTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOutlookSenderTypeEnumFromValue(v string) (*OutlookSenderTypeEnum, error) {
	ev := OutlookSenderTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OutlookSenderTypeEnum: valid values are %v", v, AllowedOutlookSenderTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OutlookSenderTypeEnum) IsValid() bool {
	for _, existing := range AllowedOutlookSenderTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OutlookSenderTypeEnum value
func (v OutlookSenderTypeEnum) Ptr() *OutlookSenderTypeEnum {
	return &v
}

type NullableOutlookSenderTypeEnum struct {
	value *OutlookSenderTypeEnum
	isSet bool
}

func (v NullableOutlookSenderTypeEnum) Get() *OutlookSenderTypeEnum {
	return v.value
}

func (v *NullableOutlookSenderTypeEnum) Set(val *OutlookSenderTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableOutlookSenderTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableOutlookSenderTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutlookSenderTypeEnum(val *OutlookSenderTypeEnum) *NullableOutlookSenderTypeEnum {
	return &NullableOutlookSenderTypeEnum{value: val, isSet: true}
}

func (v NullableOutlookSenderTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutlookSenderTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
