/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the QueryFinancialAccountsV2Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryFinancialAccountsV2Response{}

// QueryFinancialAccountsV2Response A page of the financial accounts that match the query request
type QueryFinancialAccountsV2Response struct {
	Accounts []FinancialAccount `json:"accounts,omitempty"`
	// total number of accounts matching the query, ignoring limit and offset
	TotalCount *int64 `json:"total_count,omitempty"`
	// number of accounts that were skipped in the result
	Offset *int32 `json:"offset,omitempty"`
}

// NewQueryFinancialAccountsV2Response instantiates a new QueryFinancialAccountsV2Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryFinancialAccountsV2Response() *QueryFinancialAccountsV2Response {
	this := QueryFinancialAccountsV2Response{}
	return &this
}

// NewQueryFinancialAccountsV2ResponseWithDefaults instantiates a new QueryFinancialAccountsV2Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryFinancialAccountsV2ResponseWithDefaults() *QueryFinancialAccountsV2Response {
	this := QueryFinancialAccountsV2Response{}
	return &this
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *QueryFinancialAccountsV2Response) GetAccounts() []FinancialAccount {
	if o == nil || IsNil(o.Accounts) {
		var ret []FinancialAccount
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryFinancialAccountsV2Response) GetAccountsOk() ([]FinancialAccount, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *QueryFinancialAccountsV2Response) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []FinancialAccount and assigns it to the Accounts field.
func (o *QueryFinancialAccountsV2Response) SetAccounts(v []FinancialAccount) {
	o.Accounts = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *QueryFinancialAccountsV2Response) GetTotalCount() int64 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int64
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryFinancialAccountsV2Response) GetTotalCountOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *QueryFinancialAccountsV2Response) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *QueryFinancialAccountsV2Response) SetTotalCount(v int64) {
	o.TotalCount = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *QueryFinancialAccountsV2Response) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryFinancialAccountsV2Response) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *QueryFinancialAccountsV2Response) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *QueryFinancialAccountsV2Response) SetOffset(v int32) {
	o.Offset = &v
}

func (o QueryFinancialAccountsV2Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryFinancialAccountsV2Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	if !IsNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	return toSerialize, nil
}

type NullableQueryFinancialAccountsV2Response struct {
	value *QueryFinancialAccountsV2Response
	isSet bool
}

func (v NullableQueryFinancialAccountsV2Response) Get() *QueryFinancialAccountsV2Response {
	return v.value
}

func (v *NullableQueryFinancialAccountsV2Response) Set(val *QueryFinancialAccountsV2Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryFinancialAccountsV2Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryFinancialAccountsV2Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryFinancialAccountsV2Response(val *QueryFinancialAccountsV2Response) *NullableQueryFinancialAccountsV2Response {
	return &NullableQueryFinancialAccountsV2Response{value: val, isSet: true}
}

func (v NullableQueryFinancialAccountsV2Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryFinancialAccountsV2Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
