/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the FormValidationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FormValidationRequest{}

// FormValidationRequest struct for FormValidationRequest
type FormValidationRequest struct {
	// the data that will be validated
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewFormValidationRequest instantiates a new FormValidationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFormValidationRequest() *FormValidationRequest {
	this := FormValidationRequest{}
	return &this
}

// NewFormValidationRequestWithDefaults instantiates a new FormValidationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormValidationRequestWithDefaults() *FormValidationRequest {
	this := FormValidationRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FormValidationRequest) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormValidationRequest) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FormValidationRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *FormValidationRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o FormValidationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FormValidationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableFormValidationRequest struct {
	value *FormValidationRequest
	isSet bool
}

func (v NullableFormValidationRequest) Get() *FormValidationRequest {
	return v.value
}

func (v *NullableFormValidationRequest) Set(val *FormValidationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFormValidationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFormValidationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormValidationRequest(val *FormValidationRequest) *NullableFormValidationRequest {
	return &NullableFormValidationRequest{value: val, isSet: true}
}

func (v NullableFormValidationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormValidationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
