/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateOrderStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrderStatusRequest{}

// UpdateOrderStatusRequest The data required to update the status of an order
type UpdateOrderStatusRequest struct {
	Status OrderStatusEnum `json:"status"`
}

type _UpdateOrderStatusRequest UpdateOrderStatusRequest

// NewUpdateOrderStatusRequest instantiates a new UpdateOrderStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrderStatusRequest(status OrderStatusEnum) *UpdateOrderStatusRequest {
	this := UpdateOrderStatusRequest{}
	this.Status = status
	return &this
}

// NewUpdateOrderStatusRequestWithDefaults instantiates a new UpdateOrderStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrderStatusRequestWithDefaults() *UpdateOrderStatusRequest {
	this := UpdateOrderStatusRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateOrderStatusRequest) GetStatus() OrderStatusEnum {
	if o == nil {
		var ret OrderStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateOrderStatusRequest) GetStatusOk() (*OrderStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateOrderStatusRequest) SetStatus(v OrderStatusEnum) {
	o.Status = v
}

func (o UpdateOrderStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrderStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateOrderStatusRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOrderStatusRequest := _UpdateOrderStatusRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOrderStatusRequest)

	if err != nil {
		return err
	}

	*o = UpdateOrderStatusRequest(varUpdateOrderStatusRequest)

	return err
}

type NullableUpdateOrderStatusRequest struct {
	value *UpdateOrderStatusRequest
	isSet bool
}

func (v NullableUpdateOrderStatusRequest) Get() *UpdateOrderStatusRequest {
	return v.value
}

func (v *NullableUpdateOrderStatusRequest) Set(val *UpdateOrderStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrderStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrderStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrderStatusRequest(val *UpdateOrderStatusRequest) *NullableUpdateOrderStatusRequest {
	return &NullableUpdateOrderStatusRequest{value: val, isSet: true}
}

func (v NullableUpdateOrderStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrderStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
