/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ServiceProviderAttributesPartial type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceProviderAttributesPartial{}

// ServiceProviderAttributesPartial struct for ServiceProviderAttributesPartial
type ServiceProviderAttributesPartial struct {
	// The salutation to be used for the contant person (Miss, Mister)
	Title *string `json:"title,omitempty"`
	// optional first name of contact person
	FirstName *string `json:"first_name,omitempty"`
	// optional last name of contact person
	LastName *string `json:"last_name,omitempty"`
	// the name of the company
	Company *string `json:"company,omitempty"`
	// the email address at which the company can be contacted by the platform
	Email string `json:"email"`
	// a phone number at which the company can be reached
	PhoneNumber *string              `json:"phone_number,omitempty"`
	Category    *ServiceCategoryEnum `json:"category,omitempty"`
	Address     *Address             `json:"address,omitempty"`
}

type _ServiceProviderAttributesPartial ServiceProviderAttributesPartial

// NewServiceProviderAttributesPartial instantiates a new ServiceProviderAttributesPartial object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceProviderAttributesPartial(email string) *ServiceProviderAttributesPartial {
	this := ServiceProviderAttributesPartial{}
	this.Email = email
	return &this
}

// NewServiceProviderAttributesPartialWithDefaults instantiates a new ServiceProviderAttributesPartial object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceProviderAttributesPartialWithDefaults() *ServiceProviderAttributesPartial {
	this := ServiceProviderAttributesPartial{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ServiceProviderAttributesPartial) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProviderAttributesPartial) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ServiceProviderAttributesPartial) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ServiceProviderAttributesPartial) SetTitle(v string) {
	o.Title = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *ServiceProviderAttributesPartial) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProviderAttributesPartial) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *ServiceProviderAttributesPartial) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *ServiceProviderAttributesPartial) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *ServiceProviderAttributesPartial) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProviderAttributesPartial) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *ServiceProviderAttributesPartial) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *ServiceProviderAttributesPartial) SetLastName(v string) {
	o.LastName = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *ServiceProviderAttributesPartial) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProviderAttributesPartial) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *ServiceProviderAttributesPartial) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *ServiceProviderAttributesPartial) SetCompany(v string) {
	o.Company = &v
}

// GetEmail returns the Email field value
func (o *ServiceProviderAttributesPartial) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ServiceProviderAttributesPartial) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ServiceProviderAttributesPartial) SetEmail(v string) {
	o.Email = v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *ServiceProviderAttributesPartial) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProviderAttributesPartial) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *ServiceProviderAttributesPartial) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *ServiceProviderAttributesPartial) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *ServiceProviderAttributesPartial) GetCategory() ServiceCategoryEnum {
	if o == nil || IsNil(o.Category) {
		var ret ServiceCategoryEnum
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProviderAttributesPartial) GetCategoryOk() (*ServiceCategoryEnum, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *ServiceProviderAttributesPartial) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given ServiceCategoryEnum and assigns it to the Category field.
func (o *ServiceProviderAttributesPartial) SetCategory(v ServiceCategoryEnum) {
	o.Category = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ServiceProviderAttributesPartial) GetAddress() Address {
	if o == nil || IsNil(o.Address) {
		var ret Address
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProviderAttributesPartial) GetAddressOk() (*Address, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ServiceProviderAttributesPartial) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given Address and assigns it to the Address field.
func (o *ServiceProviderAttributesPartial) SetAddress(v Address) {
	o.Address = &v
}

func (o ServiceProviderAttributesPartial) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceProviderAttributesPartial) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	toSerialize["email"] = o.Email
	if !IsNil(o.PhoneNumber) {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

func (o *ServiceProviderAttributesPartial) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceProviderAttributesPartial := _ServiceProviderAttributesPartial{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceProviderAttributesPartial)

	if err != nil {
		return err
	}

	*o = ServiceProviderAttributesPartial(varServiceProviderAttributesPartial)

	return err
}

type NullableServiceProviderAttributesPartial struct {
	value *ServiceProviderAttributesPartial
	isSet bool
}

func (v NullableServiceProviderAttributesPartial) Get() *ServiceProviderAttributesPartial {
	return v.value
}

func (v *NullableServiceProviderAttributesPartial) Set(val *ServiceProviderAttributesPartial) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceProviderAttributesPartial) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceProviderAttributesPartial) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceProviderAttributesPartial(val *ServiceProviderAttributesPartial) *NullableServiceProviderAttributesPartial {
	return &NullableServiceProviderAttributesPartial{value: val, isSet: true}
}

func (v NullableServiceProviderAttributesPartial) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceProviderAttributesPartial) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
