/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the GetNumberOfCasesForActionAndTimePeriodResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNumberOfCasesForActionAndTimePeriodResponse{}

// GetNumberOfCasesForActionAndTimePeriodResponse struct for GetNumberOfCasesForActionAndTimePeriodResponse
type GetNumberOfCasesForActionAndTimePeriodResponse struct {
	NumberOfCases *int64 `json:"number_of_cases,omitempty"`
}

// NewGetNumberOfCasesForActionAndTimePeriodResponse instantiates a new GetNumberOfCasesForActionAndTimePeriodResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNumberOfCasesForActionAndTimePeriodResponse() *GetNumberOfCasesForActionAndTimePeriodResponse {
	this := GetNumberOfCasesForActionAndTimePeriodResponse{}
	return &this
}

// NewGetNumberOfCasesForActionAndTimePeriodResponseWithDefaults instantiates a new GetNumberOfCasesForActionAndTimePeriodResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNumberOfCasesForActionAndTimePeriodResponseWithDefaults() *GetNumberOfCasesForActionAndTimePeriodResponse {
	this := GetNumberOfCasesForActionAndTimePeriodResponse{}
	return &this
}

// GetNumberOfCases returns the NumberOfCases field value if set, zero value otherwise.
func (o *GetNumberOfCasesForActionAndTimePeriodResponse) GetNumberOfCases() int64 {
	if o == nil || IsNil(o.NumberOfCases) {
		var ret int64
		return ret
	}
	return *o.NumberOfCases
}

// GetNumberOfCasesOk returns a tuple with the NumberOfCases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNumberOfCasesForActionAndTimePeriodResponse) GetNumberOfCasesOk() (*int64, bool) {
	if o == nil || IsNil(o.NumberOfCases) {
		return nil, false
	}
	return o.NumberOfCases, true
}

// HasNumberOfCases returns a boolean if a field has been set.
func (o *GetNumberOfCasesForActionAndTimePeriodResponse) HasNumberOfCases() bool {
	if o != nil && !IsNil(o.NumberOfCases) {
		return true
	}

	return false
}

// SetNumberOfCases gets a reference to the given int64 and assigns it to the NumberOfCases field.
func (o *GetNumberOfCasesForActionAndTimePeriodResponse) SetNumberOfCases(v int64) {
	o.NumberOfCases = &v
}

func (o GetNumberOfCasesForActionAndTimePeriodResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNumberOfCasesForActionAndTimePeriodResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NumberOfCases) {
		toSerialize["number_of_cases"] = o.NumberOfCases
	}
	return toSerialize, nil
}

type NullableGetNumberOfCasesForActionAndTimePeriodResponse struct {
	value *GetNumberOfCasesForActionAndTimePeriodResponse
	isSet bool
}

func (v NullableGetNumberOfCasesForActionAndTimePeriodResponse) Get() *GetNumberOfCasesForActionAndTimePeriodResponse {
	return v.value
}

func (v *NullableGetNumberOfCasesForActionAndTimePeriodResponse) Set(val *GetNumberOfCasesForActionAndTimePeriodResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNumberOfCasesForActionAndTimePeriodResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNumberOfCasesForActionAndTimePeriodResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNumberOfCasesForActionAndTimePeriodResponse(val *GetNumberOfCasesForActionAndTimePeriodResponse) *NullableGetNumberOfCasesForActionAndTimePeriodResponse {
	return &NullableGetNumberOfCasesForActionAndTimePeriodResponse{value: val, isSet: true}
}

func (v NullableGetNumberOfCasesForActionAndTimePeriodResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNumberOfCasesForActionAndTimePeriodResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
