/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AppointmentTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppointmentTemplate{}

// AppointmentTemplate struct for AppointmentTemplate
type AppointmentTemplate struct {
	// Unique and immutable ID attribute of the entity that is generated when  the instance is created. The ID is unique within the system accross all accounts and it can be used to reference the entity in other entities  or to retrieve it from the backend.
	Id string `json:"id"`
	// The name of the appointment template
	Name string `json:"name"`
	// The expression that is used to generate the name of the appointment from the data that the user has entered when booking the appointment
	NameExpression *string `json:"name_expression,omitempty"`
	// The description of the appointment template
	Description *string `json:"description,omitempty"`
	// Constrain the minimum amount of time between the scheduling and the beginning of the appointment in minutes. Set this to 10 and people won't be able to schedule an appointment that's in less than 10 minutes.
	ScheduleBefore *int32 `json:"schedule_before,omitempty"`
	// Whether we should require confirmation or not.
	RequireConfirmation *bool `json:"require_confirmation,omitempty"`
	// The number of days after which a reminder should be sent out. The list is taken as provided and a reminder will be set for the amount of days as set in the first element of the list. Once that time has passed, the reminder will be rescheduled for the next element in the list. This is repeated until the list is empty. The values in the list are considered relative to the previous reminder. So [2, 2] will send out a reminder after 2 and 4 days. The reminders will, however, not be sent out on weekends. So if the first reminder is sent out on a Friday, the second reminder will be sent out on Tuesday. To disable this option, leave the list empty.
	ConfirmationReminders []int32            `json:"confirmation_reminders,omitempty"`
	Form                  NullableCustomForm `json:"form"`
	// A flag indicating whether the entity is deleted. If the entity is deleted, it should not be returned in the results of a query, but it is still kept in the database as it is referenced by other entities.
	IsDeleted *bool `json:"is_deleted,omitempty"`
}

type _AppointmentTemplate AppointmentTemplate

// NewAppointmentTemplate instantiates a new AppointmentTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppointmentTemplate(id string, name string, form NullableCustomForm) *AppointmentTemplate {
	this := AppointmentTemplate{}
	this.Id = id
	this.Name = name
	this.Form = form
	return &this
}

// NewAppointmentTemplateWithDefaults instantiates a new AppointmentTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppointmentTemplateWithDefaults() *AppointmentTemplate {
	this := AppointmentTemplate{}
	return &this
}

// GetId returns the Id field value
func (o *AppointmentTemplate) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppointmentTemplate) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppointmentTemplate) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AppointmentTemplate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppointmentTemplate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppointmentTemplate) SetName(v string) {
	o.Name = v
}

// GetNameExpression returns the NameExpression field value if set, zero value otherwise.
func (o *AppointmentTemplate) GetNameExpression() string {
	if o == nil || IsNil(o.NameExpression) {
		var ret string
		return ret
	}
	return *o.NameExpression
}

// GetNameExpressionOk returns a tuple with the NameExpression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppointmentTemplate) GetNameExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.NameExpression) {
		return nil, false
	}
	return o.NameExpression, true
}

// HasNameExpression returns a boolean if a field has been set.
func (o *AppointmentTemplate) HasNameExpression() bool {
	if o != nil && !IsNil(o.NameExpression) {
		return true
	}

	return false
}

// SetNameExpression gets a reference to the given string and assigns it to the NameExpression field.
func (o *AppointmentTemplate) SetNameExpression(v string) {
	o.NameExpression = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AppointmentTemplate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppointmentTemplate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AppointmentTemplate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AppointmentTemplate) SetDescription(v string) {
	o.Description = &v
}

// GetScheduleBefore returns the ScheduleBefore field value if set, zero value otherwise.
func (o *AppointmentTemplate) GetScheduleBefore() int32 {
	if o == nil || IsNil(o.ScheduleBefore) {
		var ret int32
		return ret
	}
	return *o.ScheduleBefore
}

// GetScheduleBeforeOk returns a tuple with the ScheduleBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppointmentTemplate) GetScheduleBeforeOk() (*int32, bool) {
	if o == nil || IsNil(o.ScheduleBefore) {
		return nil, false
	}
	return o.ScheduleBefore, true
}

// HasScheduleBefore returns a boolean if a field has been set.
func (o *AppointmentTemplate) HasScheduleBefore() bool {
	if o != nil && !IsNil(o.ScheduleBefore) {
		return true
	}

	return false
}

// SetScheduleBefore gets a reference to the given int32 and assigns it to the ScheduleBefore field.
func (o *AppointmentTemplate) SetScheduleBefore(v int32) {
	o.ScheduleBefore = &v
}

// GetRequireConfirmation returns the RequireConfirmation field value if set, zero value otherwise.
func (o *AppointmentTemplate) GetRequireConfirmation() bool {
	if o == nil || IsNil(o.RequireConfirmation) {
		var ret bool
		return ret
	}
	return *o.RequireConfirmation
}

// GetRequireConfirmationOk returns a tuple with the RequireConfirmation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppointmentTemplate) GetRequireConfirmationOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireConfirmation) {
		return nil, false
	}
	return o.RequireConfirmation, true
}

// HasRequireConfirmation returns a boolean if a field has been set.
func (o *AppointmentTemplate) HasRequireConfirmation() bool {
	if o != nil && !IsNil(o.RequireConfirmation) {
		return true
	}

	return false
}

// SetRequireConfirmation gets a reference to the given bool and assigns it to the RequireConfirmation field.
func (o *AppointmentTemplate) SetRequireConfirmation(v bool) {
	o.RequireConfirmation = &v
}

// GetConfirmationReminders returns the ConfirmationReminders field value if set, zero value otherwise.
func (o *AppointmentTemplate) GetConfirmationReminders() []int32 {
	if o == nil || IsNil(o.ConfirmationReminders) {
		var ret []int32
		return ret
	}
	return o.ConfirmationReminders
}

// GetConfirmationRemindersOk returns a tuple with the ConfirmationReminders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppointmentTemplate) GetConfirmationRemindersOk() ([]int32, bool) {
	if o == nil || IsNil(o.ConfirmationReminders) {
		return nil, false
	}
	return o.ConfirmationReminders, true
}

// HasConfirmationReminders returns a boolean if a field has been set.
func (o *AppointmentTemplate) HasConfirmationReminders() bool {
	if o != nil && !IsNil(o.ConfirmationReminders) {
		return true
	}

	return false
}

// SetConfirmationReminders gets a reference to the given []int32 and assigns it to the ConfirmationReminders field.
func (o *AppointmentTemplate) SetConfirmationReminders(v []int32) {
	o.ConfirmationReminders = v
}

// GetForm returns the Form field value
// If the value is explicit nil, the zero value for CustomForm will be returned
func (o *AppointmentTemplate) GetForm() CustomForm {
	if o == nil || o.Form.Get() == nil {
		var ret CustomForm
		return ret
	}

	return *o.Form.Get()
}

// GetFormOk returns a tuple with the Form field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AppointmentTemplate) GetFormOk() (*CustomForm, bool) {
	if o == nil {
		return nil, false
	}
	return o.Form.Get(), o.Form.IsSet()
}

// SetForm sets field value
func (o *AppointmentTemplate) SetForm(v CustomForm) {
	o.Form.Set(&v)
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *AppointmentTemplate) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppointmentTemplate) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *AppointmentTemplate) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *AppointmentTemplate) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

func (o AppointmentTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppointmentTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.NameExpression) {
		toSerialize["name_expression"] = o.NameExpression
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ScheduleBefore) {
		toSerialize["schedule_before"] = o.ScheduleBefore
	}
	if !IsNil(o.RequireConfirmation) {
		toSerialize["require_confirmation"] = o.RequireConfirmation
	}
	if !IsNil(o.ConfirmationReminders) {
		toSerialize["confirmation_reminders"] = o.ConfirmationReminders
	}
	toSerialize["form"] = o.Form.Get()
	if !IsNil(o.IsDeleted) {
		toSerialize["is_deleted"] = o.IsDeleted
	}
	return toSerialize, nil
}

func (o *AppointmentTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"form",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppointmentTemplate := _AppointmentTemplate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppointmentTemplate)

	if err != nil {
		return err
	}

	*o = AppointmentTemplate(varAppointmentTemplate)

	return err
}

type NullableAppointmentTemplate struct {
	value *AppointmentTemplate
	isSet bool
}

func (v NullableAppointmentTemplate) Get() *AppointmentTemplate {
	return v.value
}

func (v *NullableAppointmentTemplate) Set(val *AppointmentTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableAppointmentTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableAppointmentTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppointmentTemplate(val *AppointmentTemplate) *NullableAppointmentTemplate {
	return &NullableAppointmentTemplate{value: val, isSet: true}
}

func (v NullableAppointmentTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppointmentTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
