/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ReattachInvoiceAnalysisRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReattachInvoiceAnalysisRequest{}

// ReattachInvoiceAnalysisRequest struct for ReattachInvoiceAnalysisRequest
type ReattachInvoiceAnalysisRequest struct {
	Action ReattachActionEnum `json:"action"`
	// If action is set to MOVE then this is the invoice that'll receive the pages.
	TargetId *string `json:"target_id,omitempty"`
	Pages    []int32 `json:"pages"`
}

type _ReattachInvoiceAnalysisRequest ReattachInvoiceAnalysisRequest

// NewReattachInvoiceAnalysisRequest instantiates a new ReattachInvoiceAnalysisRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReattachInvoiceAnalysisRequest(action ReattachActionEnum, pages []int32) *ReattachInvoiceAnalysisRequest {
	this := ReattachInvoiceAnalysisRequest{}
	this.Action = action
	this.Pages = pages
	return &this
}

// NewReattachInvoiceAnalysisRequestWithDefaults instantiates a new ReattachInvoiceAnalysisRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReattachInvoiceAnalysisRequestWithDefaults() *ReattachInvoiceAnalysisRequest {
	this := ReattachInvoiceAnalysisRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *ReattachInvoiceAnalysisRequest) GetAction() ReattachActionEnum {
	if o == nil {
		var ret ReattachActionEnum
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ReattachInvoiceAnalysisRequest) GetActionOk() (*ReattachActionEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ReattachInvoiceAnalysisRequest) SetAction(v ReattachActionEnum) {
	o.Action = v
}

// GetTargetId returns the TargetId field value if set, zero value otherwise.
func (o *ReattachInvoiceAnalysisRequest) GetTargetId() string {
	if o == nil || IsNil(o.TargetId) {
		var ret string
		return ret
	}
	return *o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReattachInvoiceAnalysisRequest) GetTargetIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetId) {
		return nil, false
	}
	return o.TargetId, true
}

// HasTargetId returns a boolean if a field has been set.
func (o *ReattachInvoiceAnalysisRequest) HasTargetId() bool {
	if o != nil && !IsNil(o.TargetId) {
		return true
	}

	return false
}

// SetTargetId gets a reference to the given string and assigns it to the TargetId field.
func (o *ReattachInvoiceAnalysisRequest) SetTargetId(v string) {
	o.TargetId = &v
}

// GetPages returns the Pages field value
func (o *ReattachInvoiceAnalysisRequest) GetPages() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value
// and a boolean to check if the value has been set.
func (o *ReattachInvoiceAnalysisRequest) GetPagesOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pages, true
}

// SetPages sets field value
func (o *ReattachInvoiceAnalysisRequest) SetPages(v []int32) {
	o.Pages = v
}

func (o ReattachInvoiceAnalysisRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReattachInvoiceAnalysisRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.TargetId) {
		toSerialize["target_id"] = o.TargetId
	}
	toSerialize["pages"] = o.Pages
	return toSerialize, nil
}

func (o *ReattachInvoiceAnalysisRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"pages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReattachInvoiceAnalysisRequest := _ReattachInvoiceAnalysisRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReattachInvoiceAnalysisRequest)

	if err != nil {
		return err
	}

	*o = ReattachInvoiceAnalysisRequest(varReattachInvoiceAnalysisRequest)

	return err
}

type NullableReattachInvoiceAnalysisRequest struct {
	value *ReattachInvoiceAnalysisRequest
	isSet bool
}

func (v NullableReattachInvoiceAnalysisRequest) Get() *ReattachInvoiceAnalysisRequest {
	return v.value
}

func (v *NullableReattachInvoiceAnalysisRequest) Set(val *ReattachInvoiceAnalysisRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReattachInvoiceAnalysisRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReattachInvoiceAnalysisRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReattachInvoiceAnalysisRequest(val *ReattachInvoiceAnalysisRequest) *NullableReattachInvoiceAnalysisRequest {
	return &NullableReattachInvoiceAnalysisRequest{value: val, isSet: true}
}

func (v NullableReattachInvoiceAnalysisRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReattachInvoiceAnalysisRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
