/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BankAccountAutoBookingRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankAccountAutoBookingRule{}

// BankAccountAutoBookingRule A single rule that automatically creates a booking when a newly imported bank transaction matches all of the specified matchers.
type BankAccountAutoBookingRule struct {
	// Optional human-readable label for this rule.
	Name *string `json:"name,omitempty"`
	// The ID of the BookingTemplate to execute when this rule matches.
	TemplateRef string `json:"template_ref"`
	// List of filter conditions. ALL conditions must match (AND logic) for the rule to trigger. If empty, the rule matches every imported transaction.
	Matchers []BankTransactionAutoImportFilter `json:"matchers,omitempty"`
}

type _BankAccountAutoBookingRule BankAccountAutoBookingRule

// NewBankAccountAutoBookingRule instantiates a new BankAccountAutoBookingRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankAccountAutoBookingRule(templateRef string) *BankAccountAutoBookingRule {
	this := BankAccountAutoBookingRule{}
	this.TemplateRef = templateRef
	return &this
}

// NewBankAccountAutoBookingRuleWithDefaults instantiates a new BankAccountAutoBookingRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankAccountAutoBookingRuleWithDefaults() *BankAccountAutoBookingRule {
	this := BankAccountAutoBookingRule{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BankAccountAutoBookingRule) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankAccountAutoBookingRule) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BankAccountAutoBookingRule) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BankAccountAutoBookingRule) SetName(v string) {
	o.Name = &v
}

// GetTemplateRef returns the TemplateRef field value
func (o *BankAccountAutoBookingRule) GetTemplateRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateRef
}

// GetTemplateRefOk returns a tuple with the TemplateRef field value
// and a boolean to check if the value has been set.
func (o *BankAccountAutoBookingRule) GetTemplateRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateRef, true
}

// SetTemplateRef sets field value
func (o *BankAccountAutoBookingRule) SetTemplateRef(v string) {
	o.TemplateRef = v
}

// GetMatchers returns the Matchers field value if set, zero value otherwise.
func (o *BankAccountAutoBookingRule) GetMatchers() []BankTransactionAutoImportFilter {
	if o == nil || IsNil(o.Matchers) {
		var ret []BankTransactionAutoImportFilter
		return ret
	}
	return o.Matchers
}

// GetMatchersOk returns a tuple with the Matchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankAccountAutoBookingRule) GetMatchersOk() ([]BankTransactionAutoImportFilter, bool) {
	if o == nil || IsNil(o.Matchers) {
		return nil, false
	}
	return o.Matchers, true
}

// HasMatchers returns a boolean if a field has been set.
func (o *BankAccountAutoBookingRule) HasMatchers() bool {
	if o != nil && !IsNil(o.Matchers) {
		return true
	}

	return false
}

// SetMatchers gets a reference to the given []BankTransactionAutoImportFilter and assigns it to the Matchers field.
func (o *BankAccountAutoBookingRule) SetMatchers(v []BankTransactionAutoImportFilter) {
	o.Matchers = v
}

func (o BankAccountAutoBookingRule) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankAccountAutoBookingRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["template_ref"] = o.TemplateRef
	if !IsNil(o.Matchers) {
		toSerialize["matchers"] = o.Matchers
	}
	return toSerialize, nil
}

func (o *BankAccountAutoBookingRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"template_ref",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankAccountAutoBookingRule := _BankAccountAutoBookingRule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankAccountAutoBookingRule)

	if err != nil {
		return err
	}

	*o = BankAccountAutoBookingRule(varBankAccountAutoBookingRule)

	return err
}

type NullableBankAccountAutoBookingRule struct {
	value *BankAccountAutoBookingRule
	isSet bool
}

func (v NullableBankAccountAutoBookingRule) Get() *BankAccountAutoBookingRule {
	return v.value
}

func (v *NullableBankAccountAutoBookingRule) Set(val *BankAccountAutoBookingRule) {
	v.value = val
	v.isSet = true
}

func (v NullableBankAccountAutoBookingRule) IsSet() bool {
	return v.isSet
}

func (v *NullableBankAccountAutoBookingRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankAccountAutoBookingRule(val *BankAccountAutoBookingRule) *NullableBankAccountAutoBookingRule {
	return &NullableBankAccountAutoBookingRule{value: val, isSet: true}
}

func (v NullableBankAccountAutoBookingRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankAccountAutoBookingRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
