/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the BankAccountAutoBookingConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankAccountAutoBookingConfig{}

// BankAccountAutoBookingConfig Configuration for automatic booking creation when bank transactions are imported via the nightly auto-import cron job.
type BankAccountAutoBookingConfig struct {
	// When true, auto-booking runs after each auto-import cycle for this account.
	Enabled *bool `json:"enabled,omitempty"`
	// When true, AI is used to decide if each rule matches instead of the manual matchers. The AI compares the transaction details with the template name and description to determine whether the rule applies. The first AI-approved rule wins. Matchers are ignored in this mode.
	AiMode *bool `json:"ai_mode,omitempty"`
	// Ordered list of booking rules. The first matching rule is applied (first-match wins); subsequent rules are not evaluated.
	Rules []BankAccountAutoBookingRule `json:"rules,omitempty"`
}

// NewBankAccountAutoBookingConfig instantiates a new BankAccountAutoBookingConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankAccountAutoBookingConfig() *BankAccountAutoBookingConfig {
	this := BankAccountAutoBookingConfig{}
	return &this
}

// NewBankAccountAutoBookingConfigWithDefaults instantiates a new BankAccountAutoBookingConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankAccountAutoBookingConfigWithDefaults() *BankAccountAutoBookingConfig {
	this := BankAccountAutoBookingConfig{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *BankAccountAutoBookingConfig) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankAccountAutoBookingConfig) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *BankAccountAutoBookingConfig) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *BankAccountAutoBookingConfig) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetAiMode returns the AiMode field value if set, zero value otherwise.
func (o *BankAccountAutoBookingConfig) GetAiMode() bool {
	if o == nil || IsNil(o.AiMode) {
		var ret bool
		return ret
	}
	return *o.AiMode
}

// GetAiModeOk returns a tuple with the AiMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankAccountAutoBookingConfig) GetAiModeOk() (*bool, bool) {
	if o == nil || IsNil(o.AiMode) {
		return nil, false
	}
	return o.AiMode, true
}

// HasAiMode returns a boolean if a field has been set.
func (o *BankAccountAutoBookingConfig) HasAiMode() bool {
	if o != nil && !IsNil(o.AiMode) {
		return true
	}

	return false
}

// SetAiMode gets a reference to the given bool and assigns it to the AiMode field.
func (o *BankAccountAutoBookingConfig) SetAiMode(v bool) {
	o.AiMode = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *BankAccountAutoBookingConfig) GetRules() []BankAccountAutoBookingRule {
	if o == nil || IsNil(o.Rules) {
		var ret []BankAccountAutoBookingRule
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankAccountAutoBookingConfig) GetRulesOk() ([]BankAccountAutoBookingRule, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *BankAccountAutoBookingConfig) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []BankAccountAutoBookingRule and assigns it to the Rules field.
func (o *BankAccountAutoBookingConfig) SetRules(v []BankAccountAutoBookingRule) {
	o.Rules = v
}

func (o BankAccountAutoBookingConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankAccountAutoBookingConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.AiMode) {
		toSerialize["ai_mode"] = o.AiMode
	}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	return toSerialize, nil
}

type NullableBankAccountAutoBookingConfig struct {
	value *BankAccountAutoBookingConfig
	isSet bool
}

func (v NullableBankAccountAutoBookingConfig) Get() *BankAccountAutoBookingConfig {
	return v.value
}

func (v *NullableBankAccountAutoBookingConfig) Set(val *BankAccountAutoBookingConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableBankAccountAutoBookingConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableBankAccountAutoBookingConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankAccountAutoBookingConfig(val *BankAccountAutoBookingConfig) *NullableBankAccountAutoBookingConfig {
	return &NullableBankAccountAutoBookingConfig{value: val, isSet: true}
}

func (v NullableBankAccountAutoBookingConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankAccountAutoBookingConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
