/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the QueryAppointmentSchedulesV2Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryAppointmentSchedulesV2Request{}

// QueryAppointmentSchedulesV2Request struct for QueryAppointmentSchedulesV2Request
type QueryAppointmentSchedulesV2Request struct {
	// The maximum number of entities to return from the query
	Limit *int32 `json:"limit,omitempty"`
	// The number of entities to skip before returning the result
	Offset *int32 `json:"offset,omitempty"`
	// The attribute to sort the result by. Which values are supported depends on the queried entity, an unsupported value falls back to the default sort of the query.
	SortKey   *string             `json:"sort_key,omitempty"`
	SortOrder *QuerySortOrderEnum `json:"sort_order,omitempty"`
	// Free text search term. Which attributes are matched depends on the queried entity. Multiple terms can be given separated by whitespace, in which case an entity has to match all of them.
	Search *string `json:"search,omitempty"`
	// The timestamp of the beginning of the time range
	StartTime *int64 `json:"start_time,omitempty"`
	// When true the schedules are returned without their windows and slots. Callers that only need the schedule metadata should set this, as the number of windows grows over the lifetime of a schedule.
	ExcludeWindows *bool `json:"exclude_windows,omitempty"`
	// IDs of the appointment templates the schedules were created from.
	TemplateRefs []string `json:"template_refs,omitempty"`
}

// NewQueryAppointmentSchedulesV2Request instantiates a new QueryAppointmentSchedulesV2Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryAppointmentSchedulesV2Request() *QueryAppointmentSchedulesV2Request {
	this := QueryAppointmentSchedulesV2Request{}
	return &this
}

// NewQueryAppointmentSchedulesV2RequestWithDefaults instantiates a new QueryAppointmentSchedulesV2Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryAppointmentSchedulesV2RequestWithDefaults() *QueryAppointmentSchedulesV2Request {
	this := QueryAppointmentSchedulesV2Request{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Request) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Request) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Request) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *QueryAppointmentSchedulesV2Request) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Request) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Request) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Request) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *QueryAppointmentSchedulesV2Request) SetOffset(v int32) {
	o.Offset = &v
}

// GetSortKey returns the SortKey field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Request) GetSortKey() string {
	if o == nil || IsNil(o.SortKey) {
		var ret string
		return ret
	}
	return *o.SortKey
}

// GetSortKeyOk returns a tuple with the SortKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Request) GetSortKeyOk() (*string, bool) {
	if o == nil || IsNil(o.SortKey) {
		return nil, false
	}
	return o.SortKey, true
}

// HasSortKey returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Request) HasSortKey() bool {
	if o != nil && !IsNil(o.SortKey) {
		return true
	}

	return false
}

// SetSortKey gets a reference to the given string and assigns it to the SortKey field.
func (o *QueryAppointmentSchedulesV2Request) SetSortKey(v string) {
	o.SortKey = &v
}

// GetSortOrder returns the SortOrder field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Request) GetSortOrder() QuerySortOrderEnum {
	if o == nil || IsNil(o.SortOrder) {
		var ret QuerySortOrderEnum
		return ret
	}
	return *o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Request) GetSortOrderOk() (*QuerySortOrderEnum, bool) {
	if o == nil || IsNil(o.SortOrder) {
		return nil, false
	}
	return o.SortOrder, true
}

// HasSortOrder returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Request) HasSortOrder() bool {
	if o != nil && !IsNil(o.SortOrder) {
		return true
	}

	return false
}

// SetSortOrder gets a reference to the given QuerySortOrderEnum and assigns it to the SortOrder field.
func (o *QueryAppointmentSchedulesV2Request) SetSortOrder(v QuerySortOrderEnum) {
	o.SortOrder = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Request) GetSearch() string {
	if o == nil || IsNil(o.Search) {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Request) GetSearchOk() (*string, bool) {
	if o == nil || IsNil(o.Search) {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Request) HasSearch() bool {
	if o != nil && !IsNil(o.Search) {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *QueryAppointmentSchedulesV2Request) SetSearch(v string) {
	o.Search = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Request) GetStartTime() int64 {
	if o == nil || IsNil(o.StartTime) {
		var ret int64
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Request) GetStartTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Request) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given int64 and assigns it to the StartTime field.
func (o *QueryAppointmentSchedulesV2Request) SetStartTime(v int64) {
	o.StartTime = &v
}

// GetExcludeWindows returns the ExcludeWindows field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Request) GetExcludeWindows() bool {
	if o == nil || IsNil(o.ExcludeWindows) {
		var ret bool
		return ret
	}
	return *o.ExcludeWindows
}

// GetExcludeWindowsOk returns a tuple with the ExcludeWindows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Request) GetExcludeWindowsOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeWindows) {
		return nil, false
	}
	return o.ExcludeWindows, true
}

// HasExcludeWindows returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Request) HasExcludeWindows() bool {
	if o != nil && !IsNil(o.ExcludeWindows) {
		return true
	}

	return false
}

// SetExcludeWindows gets a reference to the given bool and assigns it to the ExcludeWindows field.
func (o *QueryAppointmentSchedulesV2Request) SetExcludeWindows(v bool) {
	o.ExcludeWindows = &v
}

// GetTemplateRefs returns the TemplateRefs field value if set, zero value otherwise.
func (o *QueryAppointmentSchedulesV2Request) GetTemplateRefs() []string {
	if o == nil || IsNil(o.TemplateRefs) {
		var ret []string
		return ret
	}
	return o.TemplateRefs
}

// GetTemplateRefsOk returns a tuple with the TemplateRefs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryAppointmentSchedulesV2Request) GetTemplateRefsOk() ([]string, bool) {
	if o == nil || IsNil(o.TemplateRefs) {
		return nil, false
	}
	return o.TemplateRefs, true
}

// HasTemplateRefs returns a boolean if a field has been set.
func (o *QueryAppointmentSchedulesV2Request) HasTemplateRefs() bool {
	if o != nil && !IsNil(o.TemplateRefs) {
		return true
	}

	return false
}

// SetTemplateRefs gets a reference to the given []string and assigns it to the TemplateRefs field.
func (o *QueryAppointmentSchedulesV2Request) SetTemplateRefs(v []string) {
	o.TemplateRefs = v
}

func (o QueryAppointmentSchedulesV2Request) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryAppointmentSchedulesV2Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.SortKey) {
		toSerialize["sort_key"] = o.SortKey
	}
	if !IsNil(o.SortOrder) {
		toSerialize["sort_order"] = o.SortOrder
	}
	if !IsNil(o.Search) {
		toSerialize["search"] = o.Search
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	if !IsNil(o.ExcludeWindows) {
		toSerialize["exclude_windows"] = o.ExcludeWindows
	}
	if !IsNil(o.TemplateRefs) {
		toSerialize["template_refs"] = o.TemplateRefs
	}
	return toSerialize, nil
}

type NullableQueryAppointmentSchedulesV2Request struct {
	value *QueryAppointmentSchedulesV2Request
	isSet bool
}

func (v NullableQueryAppointmentSchedulesV2Request) Get() *QueryAppointmentSchedulesV2Request {
	return v.value
}

func (v *NullableQueryAppointmentSchedulesV2Request) Set(val *QueryAppointmentSchedulesV2Request) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryAppointmentSchedulesV2Request) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryAppointmentSchedulesV2Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryAppointmentSchedulesV2Request(val *QueryAppointmentSchedulesV2Request) *NullableQueryAppointmentSchedulesV2Request {
	return &NullableQueryAppointmentSchedulesV2Request{value: val, isSet: true}
}

func (v NullableQueryAppointmentSchedulesV2Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryAppointmentSchedulesV2Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
