/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InvoiceInputAmountDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceInputAmountDetails{}

// InvoiceInputAmountDetails struct for InvoiceInputAmountDetails
type InvoiceInputAmountDetails struct {
	// The subtotal before taxes and fees.
	SubtotalAmount float64 `json:"subtotal_amount"`
	// The total tax amount applied to the invoice
	TaxAmount *float64 `json:"tax_amount,omitempty"`
}

type _InvoiceInputAmountDetails InvoiceInputAmountDetails

// NewInvoiceInputAmountDetails instantiates a new InvoiceInputAmountDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceInputAmountDetails(subtotalAmount float64) *InvoiceInputAmountDetails {
	this := InvoiceInputAmountDetails{}
	this.SubtotalAmount = subtotalAmount
	return &this
}

// NewInvoiceInputAmountDetailsWithDefaults instantiates a new InvoiceInputAmountDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceInputAmountDetailsWithDefaults() *InvoiceInputAmountDetails {
	this := InvoiceInputAmountDetails{}
	return &this
}

// GetSubtotalAmount returns the SubtotalAmount field value
func (o *InvoiceInputAmountDetails) GetSubtotalAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.SubtotalAmount
}

// GetSubtotalAmountOk returns a tuple with the SubtotalAmount field value
// and a boolean to check if the value has been set.
func (o *InvoiceInputAmountDetails) GetSubtotalAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubtotalAmount, true
}

// SetSubtotalAmount sets field value
func (o *InvoiceInputAmountDetails) SetSubtotalAmount(v float64) {
	o.SubtotalAmount = v
}

// GetTaxAmount returns the TaxAmount field value if set, zero value otherwise.
func (o *InvoiceInputAmountDetails) GetTaxAmount() float64 {
	if o == nil || IsNil(o.TaxAmount) {
		var ret float64
		return ret
	}
	return *o.TaxAmount
}

// GetTaxAmountOk returns a tuple with the TaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceInputAmountDetails) GetTaxAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.TaxAmount) {
		return nil, false
	}
	return o.TaxAmount, true
}

// HasTaxAmount returns a boolean if a field has been set.
func (o *InvoiceInputAmountDetails) HasTaxAmount() bool {
	if o != nil && !IsNil(o.TaxAmount) {
		return true
	}

	return false
}

// SetTaxAmount gets a reference to the given float64 and assigns it to the TaxAmount field.
func (o *InvoiceInputAmountDetails) SetTaxAmount(v float64) {
	o.TaxAmount = &v
}

func (o InvoiceInputAmountDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceInputAmountDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subtotal_amount"] = o.SubtotalAmount
	if !IsNil(o.TaxAmount) {
		toSerialize["tax_amount"] = o.TaxAmount
	}
	return toSerialize, nil
}

func (o *InvoiceInputAmountDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subtotal_amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvoiceInputAmountDetails := _InvoiceInputAmountDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvoiceInputAmountDetails)

	if err != nil {
		return err
	}

	*o = InvoiceInputAmountDetails(varInvoiceInputAmountDetails)

	return err
}

type NullableInvoiceInputAmountDetails struct {
	value *InvoiceInputAmountDetails
	isSet bool
}

func (v NullableInvoiceInputAmountDetails) Get() *InvoiceInputAmountDetails {
	return v.value
}

func (v *NullableInvoiceInputAmountDetails) Set(val *InvoiceInputAmountDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceInputAmountDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceInputAmountDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceInputAmountDetails(val *InvoiceInputAmountDetails) *NullableInvoiceInputAmountDetails {
	return &NullableInvoiceInputAmountDetails{value: val, isSet: true}
}

func (v NullableInvoiceInputAmountDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceInputAmountDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
