/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the Approver type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Approver{}

// Approver Contains the details of a user who is allowed to approve the  respective approval. Either user_id or email must be provided.
type Approver struct {
	// The user ID of the user who is allowed to approve the respective approval.
	UserId *string `json:"user_id,omitempty"`
	// The email of the user who is allowed to approve the respective approval.
	Email *string `json:"email,omitempty"`
}

// NewApprover instantiates a new Approver object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprover() *Approver {
	this := Approver{}
	return &this
}

// NewApproverWithDefaults instantiates a new Approver object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproverWithDefaults() *Approver {
	this := Approver{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Approver) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Approver) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Approver) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *Approver) SetUserId(v string) {
	o.UserId = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *Approver) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Approver) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *Approver) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *Approver) SetEmail(v string) {
	o.Email = &v
}

func (o Approver) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Approver) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableApprover struct {
	value *Approver
	isSet bool
}

func (v NullableApprover) Get() *Approver {
	return v.value
}

func (v *NullableApprover) Set(val *Approver) {
	v.value = val
	v.isSet = true
}

func (v NullableApprover) IsSet() bool {
	return v.isSet
}

func (v *NullableApprover) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprover(val *Approver) *NullableApprover {
	return &NullableApprover{value: val, isSet: true}
}

func (v NullableApprover) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprover) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
