/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateConnectorConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateConnectorConfigRequest{}

// UpdateConnectorConfigRequest Request used to update a connector config
type UpdateConnectorConfigRequest struct {
	// indicates whether the connector should push data or not. While disabled the connector will not attempt to push data to the backend, however, it will continue to ping the backend to check for updates to the config.
	Enabled *bool `json:"enabled,omitempty"`
	// short description of the connector
	Description *string `json:"description,omitempty"`
	// Whether to print the logs in the backend or ignore the logs sent by the connector.
	EnableLogs *bool `json:"enable_logs,omitempty"`
	// cron expression that tells the connector how often to sync data
	SyncTime string `json:"sync_time"`
	// cron expression that tells the connector how often to ping the server and retrieve the config
	PingTime string `json:"ping_time"`
}

type _UpdateConnectorConfigRequest UpdateConnectorConfigRequest

// NewUpdateConnectorConfigRequest instantiates a new UpdateConnectorConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateConnectorConfigRequest(syncTime string, pingTime string) *UpdateConnectorConfigRequest {
	this := UpdateConnectorConfigRequest{}
	this.SyncTime = syncTime
	this.PingTime = pingTime
	return &this
}

// NewUpdateConnectorConfigRequestWithDefaults instantiates a new UpdateConnectorConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateConnectorConfigRequestWithDefaults() *UpdateConnectorConfigRequest {
	this := UpdateConnectorConfigRequest{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *UpdateConnectorConfigRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConnectorConfigRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *UpdateConnectorConfigRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *UpdateConnectorConfigRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateConnectorConfigRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConnectorConfigRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateConnectorConfigRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateConnectorConfigRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEnableLogs returns the EnableLogs field value if set, zero value otherwise.
func (o *UpdateConnectorConfigRequest) GetEnableLogs() bool {
	if o == nil || IsNil(o.EnableLogs) {
		var ret bool
		return ret
	}
	return *o.EnableLogs
}

// GetEnableLogsOk returns a tuple with the EnableLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConnectorConfigRequest) GetEnableLogsOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableLogs) {
		return nil, false
	}
	return o.EnableLogs, true
}

// HasEnableLogs returns a boolean if a field has been set.
func (o *UpdateConnectorConfigRequest) HasEnableLogs() bool {
	if o != nil && !IsNil(o.EnableLogs) {
		return true
	}

	return false
}

// SetEnableLogs gets a reference to the given bool and assigns it to the EnableLogs field.
func (o *UpdateConnectorConfigRequest) SetEnableLogs(v bool) {
	o.EnableLogs = &v
}

// GetSyncTime returns the SyncTime field value
func (o *UpdateConnectorConfigRequest) GetSyncTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SyncTime
}

// GetSyncTimeOk returns a tuple with the SyncTime field value
// and a boolean to check if the value has been set.
func (o *UpdateConnectorConfigRequest) GetSyncTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SyncTime, true
}

// SetSyncTime sets field value
func (o *UpdateConnectorConfigRequest) SetSyncTime(v string) {
	o.SyncTime = v
}

// GetPingTime returns the PingTime field value
func (o *UpdateConnectorConfigRequest) GetPingTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PingTime
}

// GetPingTimeOk returns a tuple with the PingTime field value
// and a boolean to check if the value has been set.
func (o *UpdateConnectorConfigRequest) GetPingTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PingTime, true
}

// SetPingTime sets field value
func (o *UpdateConnectorConfigRequest) SetPingTime(v string) {
	o.PingTime = v
}

func (o UpdateConnectorConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateConnectorConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EnableLogs) {
		toSerialize["enable_logs"] = o.EnableLogs
	}
	toSerialize["sync_time"] = o.SyncTime
	toSerialize["ping_time"] = o.PingTime
	return toSerialize, nil
}

func (o *UpdateConnectorConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sync_time",
		"ping_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateConnectorConfigRequest := _UpdateConnectorConfigRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateConnectorConfigRequest)

	if err != nil {
		return err
	}

	*o = UpdateConnectorConfigRequest(varUpdateConnectorConfigRequest)

	return err
}

type NullableUpdateConnectorConfigRequest struct {
	value *UpdateConnectorConfigRequest
	isSet bool
}

func (v NullableUpdateConnectorConfigRequest) Get() *UpdateConnectorConfigRequest {
	return v.value
}

func (v *NullableUpdateConnectorConfigRequest) Set(val *UpdateConnectorConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateConnectorConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateConnectorConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateConnectorConfigRequest(val *UpdateConnectorConfigRequest) *NullableUpdateConnectorConfigRequest {
	return &NullableUpdateConnectorConfigRequest{value: val, isSet: true}
}

func (v NullableUpdateConnectorConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateConnectorConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
