/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkflowInitStepDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowInitStepDefinition{}

// WorkflowInitStepDefinition the definition of a step of a workflow that will be executed before the workflow is started
type WorkflowInitStepDefinition struct {
	// the ID of the step, unique within the workflow. This is used to handle  the flow of the workflow execution.
	Id string `json:"id"`
	// the type of the step, which defines how it will be rendered in the UI and how it will be executed in the backend.
	Type string `json:"type"`
	// a parameter of a workflow step or step action. The value of the parameter is contextual and can vary in type and meaning depending on the step or action that uses it. If used in a step, the parameter will be available in the UI and will not be interpreted, i.e. JS expressions are not allowed. In actions however, the parameter might be interpreted as a JS expression, if the action type requires it.
	Parameters map[string]interface{} `json:"parameters,omitempty"`
	MenuWidget WidgetDescriptor       `json:"menu_widget"`
	// Optional ID of the group of the step. If a group is provided, steps within the same group will be grouped together in the UI as a drawer.
	GroupRef *string `json:"group_ref,omitempty"`
	// a map of values, where the key and values are strings
	DynamicParameters *map[string]string             `json:"dynamic_parameters,omitempty"`
	Actions           []WorkflowStepActionDefinition `json:"actions"`
	// optional JS script that will be executed in the backend to generate the data for the step,  before being sent over to the UI. This can be used to generate dynamic data for the step,  based on the context of the workflow execution.
	DataScript *string `json:"data_script,omitempty"`
}

type _WorkflowInitStepDefinition WorkflowInitStepDefinition

// NewWorkflowInitStepDefinition instantiates a new WorkflowInitStepDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowInitStepDefinition(id string, type_ string, menuWidget WidgetDescriptor, actions []WorkflowStepActionDefinition) *WorkflowInitStepDefinition {
	this := WorkflowInitStepDefinition{}
	this.Id = id
	this.Type = type_
	this.MenuWidget = menuWidget
	this.Actions = actions
	return &this
}

// NewWorkflowInitStepDefinitionWithDefaults instantiates a new WorkflowInitStepDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowInitStepDefinitionWithDefaults() *WorkflowInitStepDefinition {
	this := WorkflowInitStepDefinition{}
	return &this
}

// GetId returns the Id field value
func (o *WorkflowInitStepDefinition) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepDefinition) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkflowInitStepDefinition) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *WorkflowInitStepDefinition) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepDefinition) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WorkflowInitStepDefinition) SetType(v string) {
	o.Type = v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *WorkflowInitStepDefinition) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepDefinition) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *WorkflowInitStepDefinition) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *WorkflowInitStepDefinition) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

// GetMenuWidget returns the MenuWidget field value
func (o *WorkflowInitStepDefinition) GetMenuWidget() WidgetDescriptor {
	if o == nil {
		var ret WidgetDescriptor
		return ret
	}

	return o.MenuWidget
}

// GetMenuWidgetOk returns a tuple with the MenuWidget field value
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepDefinition) GetMenuWidgetOk() (*WidgetDescriptor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MenuWidget, true
}

// SetMenuWidget sets field value
func (o *WorkflowInitStepDefinition) SetMenuWidget(v WidgetDescriptor) {
	o.MenuWidget = v
}

// GetGroupRef returns the GroupRef field value if set, zero value otherwise.
func (o *WorkflowInitStepDefinition) GetGroupRef() string {
	if o == nil || IsNil(o.GroupRef) {
		var ret string
		return ret
	}
	return *o.GroupRef
}

// GetGroupRefOk returns a tuple with the GroupRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepDefinition) GetGroupRefOk() (*string, bool) {
	if o == nil || IsNil(o.GroupRef) {
		return nil, false
	}
	return o.GroupRef, true
}

// HasGroupRef returns a boolean if a field has been set.
func (o *WorkflowInitStepDefinition) HasGroupRef() bool {
	if o != nil && !IsNil(o.GroupRef) {
		return true
	}

	return false
}

// SetGroupRef gets a reference to the given string and assigns it to the GroupRef field.
func (o *WorkflowInitStepDefinition) SetGroupRef(v string) {
	o.GroupRef = &v
}

// GetDynamicParameters returns the DynamicParameters field value if set, zero value otherwise.
func (o *WorkflowInitStepDefinition) GetDynamicParameters() map[string]string {
	if o == nil || IsNil(o.DynamicParameters) {
		var ret map[string]string
		return ret
	}
	return *o.DynamicParameters
}

// GetDynamicParametersOk returns a tuple with the DynamicParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepDefinition) GetDynamicParametersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.DynamicParameters) {
		return nil, false
	}
	return o.DynamicParameters, true
}

// HasDynamicParameters returns a boolean if a field has been set.
func (o *WorkflowInitStepDefinition) HasDynamicParameters() bool {
	if o != nil && !IsNil(o.DynamicParameters) {
		return true
	}

	return false
}

// SetDynamicParameters gets a reference to the given map[string]string and assigns it to the DynamicParameters field.
func (o *WorkflowInitStepDefinition) SetDynamicParameters(v map[string]string) {
	o.DynamicParameters = &v
}

// GetActions returns the Actions field value
func (o *WorkflowInitStepDefinition) GetActions() []WorkflowStepActionDefinition {
	if o == nil {
		var ret []WorkflowStepActionDefinition
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepDefinition) GetActionsOk() ([]WorkflowStepActionDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *WorkflowInitStepDefinition) SetActions(v []WorkflowStepActionDefinition) {
	o.Actions = v
}

// GetDataScript returns the DataScript field value if set, zero value otherwise.
func (o *WorkflowInitStepDefinition) GetDataScript() string {
	if o == nil || IsNil(o.DataScript) {
		var ret string
		return ret
	}
	return *o.DataScript
}

// GetDataScriptOk returns a tuple with the DataScript field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepDefinition) GetDataScriptOk() (*string, bool) {
	if o == nil || IsNil(o.DataScript) {
		return nil, false
	}
	return o.DataScript, true
}

// HasDataScript returns a boolean if a field has been set.
func (o *WorkflowInitStepDefinition) HasDataScript() bool {
	if o != nil && !IsNil(o.DataScript) {
		return true
	}

	return false
}

// SetDataScript gets a reference to the given string and assigns it to the DataScript field.
func (o *WorkflowInitStepDefinition) SetDataScript(v string) {
	o.DataScript = &v
}

func (o WorkflowInitStepDefinition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowInitStepDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	toSerialize["menu_widget"] = o.MenuWidget
	if !IsNil(o.GroupRef) {
		toSerialize["group_ref"] = o.GroupRef
	}
	if !IsNil(o.DynamicParameters) {
		toSerialize["dynamic_parameters"] = o.DynamicParameters
	}
	toSerialize["actions"] = o.Actions
	if !IsNil(o.DataScript) {
		toSerialize["data_script"] = o.DataScript
	}
	return toSerialize, nil
}

func (o *WorkflowInitStepDefinition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"menu_widget",
		"actions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowInitStepDefinition := _WorkflowInitStepDefinition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowInitStepDefinition)

	if err != nil {
		return err
	}

	*o = WorkflowInitStepDefinition(varWorkflowInitStepDefinition)

	return err
}

type NullableWorkflowInitStepDefinition struct {
	value *WorkflowInitStepDefinition
	isSet bool
}

func (v NullableWorkflowInitStepDefinition) Get() *WorkflowInitStepDefinition {
	return v.value
}

func (v *NullableWorkflowInitStepDefinition) Set(val *WorkflowInitStepDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowInitStepDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowInitStepDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowInitStepDefinition(val *WorkflowInitStepDefinition) *NullableWorkflowInitStepDefinition {
	return &NullableWorkflowInitStepDefinition{value: val, isSet: true}
}

func (v NullableWorkflowInitStepDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowInitStepDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
