/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// CreateConnectorConfigRequest Request used to update a connector config
type CreateConnectorConfigRequest struct {
	// id of the connector
	ConnectorId *string `json:"connector_id,omitempty"`
	// short description of the connector
	Description *string `json:"description,omitempty"`
	// indicates whether the connector should push data or not. While disabled the connector will not attempt to push data to the backend, however, it  will continue to ping the backend to check for updates to the config.
	Enabled *bool `json:"enabled,omitempty"`
	// cron expression that tells the connector how often to sync data
	SyncTimes *string `json:"sync_times,omitempty"`
	// cron expression that tells the connector how often to ping the server and  retrieve the config
	PingTimes *string `json:"ping_times,omitempty"`
	// list of entities to be synchronised
	Entities []string               `json:"entities,omitempty"`
	LogLevel *ConnectorLogLevelEnum `json:"log_level,omitempty"`
}

// NewCreateConnectorConfigRequest instantiates a new CreateConnectorConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateConnectorConfigRequest() *CreateConnectorConfigRequest {
	this := CreateConnectorConfigRequest{}
	return &this
}

// NewCreateConnectorConfigRequestWithDefaults instantiates a new CreateConnectorConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateConnectorConfigRequestWithDefaults() *CreateConnectorConfigRequest {
	this := CreateConnectorConfigRequest{}
	return &this
}

// GetConnectorId returns the ConnectorId field value if set, zero value otherwise.
func (o *CreateConnectorConfigRequest) GetConnectorId() string {
	if o == nil || o.ConnectorId == nil {
		var ret string
		return ret
	}
	return *o.ConnectorId
}

// GetConnectorIdOk returns a tuple with the ConnectorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorConfigRequest) GetConnectorIdOk() (*string, bool) {
	if o == nil || o.ConnectorId == nil {
		return nil, false
	}
	return o.ConnectorId, true
}

// HasConnectorId returns a boolean if a field has been set.
func (o *CreateConnectorConfigRequest) HasConnectorId() bool {
	if o != nil && o.ConnectorId != nil {
		return true
	}

	return false
}

// SetConnectorId gets a reference to the given string and assigns it to the ConnectorId field.
func (o *CreateConnectorConfigRequest) SetConnectorId(v string) {
	o.ConnectorId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateConnectorConfigRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorConfigRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateConnectorConfigRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateConnectorConfigRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateConnectorConfigRequest) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorConfigRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateConnectorConfigRequest) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateConnectorConfigRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetSyncTimes returns the SyncTimes field value if set, zero value otherwise.
func (o *CreateConnectorConfigRequest) GetSyncTimes() string {
	if o == nil || o.SyncTimes == nil {
		var ret string
		return ret
	}
	return *o.SyncTimes
}

// GetSyncTimesOk returns a tuple with the SyncTimes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorConfigRequest) GetSyncTimesOk() (*string, bool) {
	if o == nil || o.SyncTimes == nil {
		return nil, false
	}
	return o.SyncTimes, true
}

// HasSyncTimes returns a boolean if a field has been set.
func (o *CreateConnectorConfigRequest) HasSyncTimes() bool {
	if o != nil && o.SyncTimes != nil {
		return true
	}

	return false
}

// SetSyncTimes gets a reference to the given string and assigns it to the SyncTimes field.
func (o *CreateConnectorConfigRequest) SetSyncTimes(v string) {
	o.SyncTimes = &v
}

// GetPingTimes returns the PingTimes field value if set, zero value otherwise.
func (o *CreateConnectorConfigRequest) GetPingTimes() string {
	if o == nil || o.PingTimes == nil {
		var ret string
		return ret
	}
	return *o.PingTimes
}

// GetPingTimesOk returns a tuple with the PingTimes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorConfigRequest) GetPingTimesOk() (*string, bool) {
	if o == nil || o.PingTimes == nil {
		return nil, false
	}
	return o.PingTimes, true
}

// HasPingTimes returns a boolean if a field has been set.
func (o *CreateConnectorConfigRequest) HasPingTimes() bool {
	if o != nil && o.PingTimes != nil {
		return true
	}

	return false
}

// SetPingTimes gets a reference to the given string and assigns it to the PingTimes field.
func (o *CreateConnectorConfigRequest) SetPingTimes(v string) {
	o.PingTimes = &v
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *CreateConnectorConfigRequest) GetEntities() []string {
	if o == nil || o.Entities == nil {
		var ret []string
		return ret
	}
	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorConfigRequest) GetEntitiesOk() ([]string, bool) {
	if o == nil || o.Entities == nil {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *CreateConnectorConfigRequest) HasEntities() bool {
	if o != nil && o.Entities != nil {
		return true
	}

	return false
}

// SetEntities gets a reference to the given []string and assigns it to the Entities field.
func (o *CreateConnectorConfigRequest) SetEntities(v []string) {
	o.Entities = v
}

// GetLogLevel returns the LogLevel field value if set, zero value otherwise.
func (o *CreateConnectorConfigRequest) GetLogLevel() ConnectorLogLevelEnum {
	if o == nil || o.LogLevel == nil {
		var ret ConnectorLogLevelEnum
		return ret
	}
	return *o.LogLevel
}

// GetLogLevelOk returns a tuple with the LogLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateConnectorConfigRequest) GetLogLevelOk() (*ConnectorLogLevelEnum, bool) {
	if o == nil || o.LogLevel == nil {
		return nil, false
	}
	return o.LogLevel, true
}

// HasLogLevel returns a boolean if a field has been set.
func (o *CreateConnectorConfigRequest) HasLogLevel() bool {
	if o != nil && o.LogLevel != nil {
		return true
	}

	return false
}

// SetLogLevel gets a reference to the given ConnectorLogLevelEnum and assigns it to the LogLevel field.
func (o *CreateConnectorConfigRequest) SetLogLevel(v ConnectorLogLevelEnum) {
	o.LogLevel = &v
}

func (o CreateConnectorConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ConnectorId != nil {
		toSerialize["connector_id"] = o.ConnectorId
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.SyncTimes != nil {
		toSerialize["sync_times"] = o.SyncTimes
	}
	if o.PingTimes != nil {
		toSerialize["ping_times"] = o.PingTimes
	}
	if o.Entities != nil {
		toSerialize["entities"] = o.Entities
	}
	if o.LogLevel != nil {
		toSerialize["log_level"] = o.LogLevel
	}
	return json.Marshal(toSerialize)
}

type NullableCreateConnectorConfigRequest struct {
	value *CreateConnectorConfigRequest
	isSet bool
}

func (v NullableCreateConnectorConfigRequest) Get() *CreateConnectorConfigRequest {
	return v.value
}

func (v *NullableCreateConnectorConfigRequest) Set(val *CreateConnectorConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateConnectorConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateConnectorConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateConnectorConfigRequest(val *CreateConnectorConfigRequest) *NullableCreateConnectorConfigRequest {
	return &NullableCreateConnectorConfigRequest{value: val, isSet: true}
}

func (v NullableCreateConnectorConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateConnectorConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
