/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// BalanceCadenceEnum the model 'BalanceCadenceEnum'
type BalanceCadenceEnum string

// List of BalanceCadenceEnum
const (
	BALANCECADENCEENUM_YEARLY_CADENCE  BalanceCadenceEnum = "yearly_cadence"
	BALANCECADENCEENUM_MONTHLY_CADENCE BalanceCadenceEnum = "monthly_cadence"
	BALANCECADENCEENUM_DAILY_CADENCE   BalanceCadenceEnum = "daily_cadence"
)

// All allowed values of BalanceCadenceEnum enum
var AllowedBalanceCadenceEnumEnumValues = []BalanceCadenceEnum{
	"yearly_cadence",
	"monthly_cadence",
	"daily_cadence",
}

func (v *BalanceCadenceEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BalanceCadenceEnum(value)
	for _, existing := range AllowedBalanceCadenceEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BalanceCadenceEnum", value)
}

// NewBalanceCadenceEnumFromValue returns a pointer to a valid BalanceCadenceEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBalanceCadenceEnumFromValue(v string) (*BalanceCadenceEnum, error) {
	ev := BalanceCadenceEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BalanceCadenceEnum: valid values are %v", v, AllowedBalanceCadenceEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BalanceCadenceEnum) IsValid() bool {
	for _, existing := range AllowedBalanceCadenceEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BalanceCadenceEnum value
func (v BalanceCadenceEnum) Ptr() *BalanceCadenceEnum {
	return &v
}

type NullableBalanceCadenceEnum struct {
	value *BalanceCadenceEnum
	isSet bool
}

func (v NullableBalanceCadenceEnum) Get() *BalanceCadenceEnum {
	return v.value
}

func (v *NullableBalanceCadenceEnum) Set(val *BalanceCadenceEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableBalanceCadenceEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableBalanceCadenceEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalanceCadenceEnum(val *BalanceCadenceEnum) *NullableBalanceCadenceEnum {
	return &NullableBalanceCadenceEnum{value: val, isSet: true}
}

func (v NullableBalanceCadenceEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalanceCadenceEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
