/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the UpdateBookingPreviewRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateBookingPreviewRequest{}

// UpdateBookingPreviewRequest Request used to update a booking preview. The caller must specify exactly one of the fields to update. If the input_data is updated, the bookings will be re-generated based on the new input data. if bookings are updated, the provided bookings will replace the existing ones.
type UpdateBookingPreviewRequest struct {
	// If provided, the input data for the preview will be updated, and the bookings will be re-generated based on the new input data. Only applicable for template-based previews.
	InputData map[string]interface{} `json:"input_data,omitempty"`
	// If provided, the bookings of the preview will be replaced with the provided ones.
	Bookings []AccountBooking `json:"bookings,omitempty"`
}

// NewUpdateBookingPreviewRequest instantiates a new UpdateBookingPreviewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBookingPreviewRequest() *UpdateBookingPreviewRequest {
	this := UpdateBookingPreviewRequest{}
	return &this
}

// NewUpdateBookingPreviewRequestWithDefaults instantiates a new UpdateBookingPreviewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBookingPreviewRequestWithDefaults() *UpdateBookingPreviewRequest {
	this := UpdateBookingPreviewRequest{}
	return &this
}

// GetInputData returns the InputData field value if set, zero value otherwise.
func (o *UpdateBookingPreviewRequest) GetInputData() map[string]interface{} {
	if o == nil || IsNil(o.InputData) {
		var ret map[string]interface{}
		return ret
	}
	return o.InputData
}

// GetInputDataOk returns a tuple with the InputData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBookingPreviewRequest) GetInputDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.InputData) {
		return map[string]interface{}{}, false
	}
	return o.InputData, true
}

// HasInputData returns a boolean if a field has been set.
func (o *UpdateBookingPreviewRequest) HasInputData() bool {
	if o != nil && !IsNil(o.InputData) {
		return true
	}

	return false
}

// SetInputData gets a reference to the given map[string]interface{} and assigns it to the InputData field.
func (o *UpdateBookingPreviewRequest) SetInputData(v map[string]interface{}) {
	o.InputData = v
}

// GetBookings returns the Bookings field value if set, zero value otherwise.
func (o *UpdateBookingPreviewRequest) GetBookings() []AccountBooking {
	if o == nil || IsNil(o.Bookings) {
		var ret []AccountBooking
		return ret
	}
	return o.Bookings
}

// GetBookingsOk returns a tuple with the Bookings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBookingPreviewRequest) GetBookingsOk() ([]AccountBooking, bool) {
	if o == nil || IsNil(o.Bookings) {
		return nil, false
	}
	return o.Bookings, true
}

// HasBookings returns a boolean if a field has been set.
func (o *UpdateBookingPreviewRequest) HasBookings() bool {
	if o != nil && !IsNil(o.Bookings) {
		return true
	}

	return false
}

// SetBookings gets a reference to the given []AccountBooking and assigns it to the Bookings field.
func (o *UpdateBookingPreviewRequest) SetBookings(v []AccountBooking) {
	o.Bookings = v
}

func (o UpdateBookingPreviewRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateBookingPreviewRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InputData) {
		toSerialize["input_data"] = o.InputData
	}
	if !IsNil(o.Bookings) {
		toSerialize["bookings"] = o.Bookings
	}
	return toSerialize, nil
}

type NullableUpdateBookingPreviewRequest struct {
	value *UpdateBookingPreviewRequest
	isSet bool
}

func (v NullableUpdateBookingPreviewRequest) Get() *UpdateBookingPreviewRequest {
	return v.value
}

func (v *NullableUpdateBookingPreviewRequest) Set(val *UpdateBookingPreviewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBookingPreviewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBookingPreviewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBookingPreviewRequest(val *UpdateBookingPreviewRequest) *NullableUpdateBookingPreviewRequest {
	return &NullableUpdateBookingPreviewRequest{value: val, isSet: true}
}

func (v NullableUpdateBookingPreviewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBookingPreviewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
