/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// ThumbnailStatusEnum Whether a thumbnail can be expected for an attachment. Thumbnails are rendered in the background, so a freshly uploaded file reports 'pending' until the rendering has finished.
type ThumbnailStatusEnum string

// List of ThumbnailStatusEnum
const (
	THUMBNAILSTATUSENUM_NONE    ThumbnailStatusEnum = "none"
	THUMBNAILSTATUSENUM_PENDING ThumbnailStatusEnum = "pending"
	THUMBNAILSTATUSENUM_READY   ThumbnailStatusEnum = "ready"
)

// All allowed values of ThumbnailStatusEnum enum
var AllowedThumbnailStatusEnumEnumValues = []ThumbnailStatusEnum{
	"none",
	"pending",
	"ready",
}

func (v *ThumbnailStatusEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ThumbnailStatusEnum(value)
	for _, existing := range AllowedThumbnailStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ThumbnailStatusEnum", value)
}

// NewThumbnailStatusEnumFromValue returns a pointer to a valid ThumbnailStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewThumbnailStatusEnumFromValue(v string) (*ThumbnailStatusEnum, error) {
	ev := ThumbnailStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ThumbnailStatusEnum: valid values are %v", v, AllowedThumbnailStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ThumbnailStatusEnum) IsValid() bool {
	for _, existing := range AllowedThumbnailStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ThumbnailStatusEnum value
func (v ThumbnailStatusEnum) Ptr() *ThumbnailStatusEnum {
	return &v
}

type NullableThumbnailStatusEnum struct {
	value *ThumbnailStatusEnum
	isSet bool
}

func (v NullableThumbnailStatusEnum) Get() *ThumbnailStatusEnum {
	return v.value
}

func (v *NullableThumbnailStatusEnum) Set(val *ThumbnailStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableThumbnailStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableThumbnailStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThumbnailStatusEnum(val *ThumbnailStatusEnum) *NullableThumbnailStatusEnum {
	return &NullableThumbnailStatusEnum{value: val, isSet: true}
}

func (v NullableThumbnailStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThumbnailStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
