/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// ChatbotMessageRole The originator of a chat message. USER is the (public) tenant talking to the chatbot, ASSISTANT is the chatbot itself.
type ChatbotMessageRole string

// List of ChatbotMessageRole
const (
	CHATBOTMESSAGEROLE_USER      ChatbotMessageRole = "USER"
	CHATBOTMESSAGEROLE_ASSISTANT ChatbotMessageRole = "ASSISTANT"
)

// All allowed values of ChatbotMessageRole enum
var AllowedChatbotMessageRoleEnumValues = []ChatbotMessageRole{
	"USER",
	"ASSISTANT",
}

func (v *ChatbotMessageRole) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ChatbotMessageRole(value)
	for _, existing := range AllowedChatbotMessageRoleEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ChatbotMessageRole", value)
}

// NewChatbotMessageRoleFromValue returns a pointer to a valid ChatbotMessageRole
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewChatbotMessageRoleFromValue(v string) (*ChatbotMessageRole, error) {
	ev := ChatbotMessageRole(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ChatbotMessageRole: valid values are %v", v, AllowedChatbotMessageRoleEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ChatbotMessageRole) IsValid() bool {
	for _, existing := range AllowedChatbotMessageRoleEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ChatbotMessageRole value
func (v ChatbotMessageRole) Ptr() *ChatbotMessageRole {
	return &v
}

type NullableChatbotMessageRole struct {
	value *ChatbotMessageRole
	isSet bool
}

func (v NullableChatbotMessageRole) Get() *ChatbotMessageRole {
	return v.value
}

func (v *NullableChatbotMessageRole) Set(val *ChatbotMessageRole) {
	v.value = val
	v.isSet = true
}

func (v NullableChatbotMessageRole) IsSet() bool {
	return v.isSet
}

func (v *NullableChatbotMessageRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatbotMessageRole(val *ChatbotMessageRole) *NullableChatbotMessageRole {
	return &NullableChatbotMessageRole{value: val, isSet: true}
}

func (v NullableChatbotMessageRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatbotMessageRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
