/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// RevenueTypeScopeEnum The scope where a revenue type is used.
type RevenueTypeScopeEnum string

// List of RevenueTypeScopeEnum
const (
	REVENUETYPESCOPEENUM_TENANCY   RevenueTypeScopeEnum = "tenancy"
	REVENUETYPESCOPEENUM_OWNERSHIP RevenueTypeScopeEnum = "ownership"
	REVENUETYPESCOPEENUM_PROPERTY  RevenueTypeScopeEnum = "property"
)

// All allowed values of RevenueTypeScopeEnum enum
var AllowedRevenueTypeScopeEnumEnumValues = []RevenueTypeScopeEnum{
	"tenancy",
	"ownership",
	"property",
}

func (v *RevenueTypeScopeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RevenueTypeScopeEnum(value)
	for _, existing := range AllowedRevenueTypeScopeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RevenueTypeScopeEnum", value)
}

// NewRevenueTypeScopeEnumFromValue returns a pointer to a valid RevenueTypeScopeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRevenueTypeScopeEnumFromValue(v string) (*RevenueTypeScopeEnum, error) {
	ev := RevenueTypeScopeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RevenueTypeScopeEnum: valid values are %v", v, AllowedRevenueTypeScopeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RevenueTypeScopeEnum) IsValid() bool {
	for _, existing := range AllowedRevenueTypeScopeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RevenueTypeScopeEnum value
func (v RevenueTypeScopeEnum) Ptr() *RevenueTypeScopeEnum {
	return &v
}

type NullableRevenueTypeScopeEnum struct {
	value *RevenueTypeScopeEnum
	isSet bool
}

func (v NullableRevenueTypeScopeEnum) Get() *RevenueTypeScopeEnum {
	return v.value
}

func (v *NullableRevenueTypeScopeEnum) Set(val *RevenueTypeScopeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableRevenueTypeScopeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableRevenueTypeScopeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevenueTypeScopeEnum(val *RevenueTypeScopeEnum) *NullableRevenueTypeScopeEnum {
	return &NullableRevenueTypeScopeEnum{value: val, isSet: true}
}

func (v NullableRevenueTypeScopeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevenueTypeScopeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
