/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// DataExportAlignmentEnum The horizontal alignment of the values of a column
type DataExportAlignmentEnum string

// List of DataExportAlignmentEnum
const (
	DATAEXPORTALIGNMENTENUM_LEFT   DataExportAlignmentEnum = "LEFT"
	DATAEXPORTALIGNMENTENUM_CENTER DataExportAlignmentEnum = "CENTER"
	DATAEXPORTALIGNMENTENUM_RIGHT  DataExportAlignmentEnum = "RIGHT"
)

// All allowed values of DataExportAlignmentEnum enum
var AllowedDataExportAlignmentEnumEnumValues = []DataExportAlignmentEnum{
	"LEFT",
	"CENTER",
	"RIGHT",
}

func (v *DataExportAlignmentEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DataExportAlignmentEnum(value)
	for _, existing := range AllowedDataExportAlignmentEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DataExportAlignmentEnum", value)
}

// NewDataExportAlignmentEnumFromValue returns a pointer to a valid DataExportAlignmentEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDataExportAlignmentEnumFromValue(v string) (*DataExportAlignmentEnum, error) {
	ev := DataExportAlignmentEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DataExportAlignmentEnum: valid values are %v", v, AllowedDataExportAlignmentEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DataExportAlignmentEnum) IsValid() bool {
	for _, existing := range AllowedDataExportAlignmentEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DataExportAlignmentEnum value
func (v DataExportAlignmentEnum) Ptr() *DataExportAlignmentEnum {
	return &v
}

type NullableDataExportAlignmentEnum struct {
	value *DataExportAlignmentEnum
	isSet bool
}

func (v NullableDataExportAlignmentEnum) Get() *DataExportAlignmentEnum {
	return v.value
}

func (v *NullableDataExportAlignmentEnum) Set(val *DataExportAlignmentEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableDataExportAlignmentEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableDataExportAlignmentEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataExportAlignmentEnum(val *DataExportAlignmentEnum) *NullableDataExportAlignmentEnum {
	return &NullableDataExportAlignmentEnum{value: val, isSet: true}
}

func (v NullableDataExportAlignmentEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataExportAlignmentEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
