/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the GenerateAiCommentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateAiCommentResponse{}

// GenerateAiCommentResponse AI-generated comment suggestions
type GenerateAiCommentResponse struct {
	Options []string `json:"options,omitempty"`
}

// NewGenerateAiCommentResponse instantiates a new GenerateAiCommentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateAiCommentResponse() *GenerateAiCommentResponse {
	this := GenerateAiCommentResponse{}
	return &this
}

// NewGenerateAiCommentResponseWithDefaults instantiates a new GenerateAiCommentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateAiCommentResponseWithDefaults() *GenerateAiCommentResponse {
	this := GenerateAiCommentResponse{}
	return &this
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *GenerateAiCommentResponse) GetOptions() []string {
	if o == nil || IsNil(o.Options) {
		var ret []string
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateAiCommentResponse) GetOptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *GenerateAiCommentResponse) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []string and assigns it to the Options field.
func (o *GenerateAiCommentResponse) SetOptions(v []string) {
	o.Options = v
}

func (o GenerateAiCommentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateAiCommentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableGenerateAiCommentResponse struct {
	value *GenerateAiCommentResponse
	isSet bool
}

func (v NullableGenerateAiCommentResponse) Get() *GenerateAiCommentResponse {
	return v.value
}

func (v *NullableGenerateAiCommentResponse) Set(val *GenerateAiCommentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateAiCommentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateAiCommentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateAiCommentResponse(val *GenerateAiCommentResponse) *NullableGenerateAiCommentResponse {
	return &NullableGenerateAiCommentResponse{value: val, isSet: true}
}

func (v NullableGenerateAiCommentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateAiCommentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
