/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QueryAllocationQuantityRequirementsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryAllocationQuantityRequirementsRequest{}

// QueryAllocationQuantityRequirementsRequest struct for QueryAllocationQuantityRequirementsRequest
type QueryAllocationQuantityRequirementsRequest struct {
	// ID of the building.
	PropertyRef   string `json:"property_ref"`
	FiscalYearRef string `json:"fiscal_year_ref"`
}

type _QueryAllocationQuantityRequirementsRequest QueryAllocationQuantityRequirementsRequest

// NewQueryAllocationQuantityRequirementsRequest instantiates a new QueryAllocationQuantityRequirementsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryAllocationQuantityRequirementsRequest(propertyRef string, fiscalYearRef string) *QueryAllocationQuantityRequirementsRequest {
	this := QueryAllocationQuantityRequirementsRequest{}
	this.PropertyRef = propertyRef
	this.FiscalYearRef = fiscalYearRef
	return &this
}

// NewQueryAllocationQuantityRequirementsRequestWithDefaults instantiates a new QueryAllocationQuantityRequirementsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryAllocationQuantityRequirementsRequestWithDefaults() *QueryAllocationQuantityRequirementsRequest {
	this := QueryAllocationQuantityRequirementsRequest{}
	return &this
}

// GetPropertyRef returns the PropertyRef field value
func (o *QueryAllocationQuantityRequirementsRequest) GetPropertyRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PropertyRef
}

// GetPropertyRefOk returns a tuple with the PropertyRef field value
// and a boolean to check if the value has been set.
func (o *QueryAllocationQuantityRequirementsRequest) GetPropertyRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PropertyRef, true
}

// SetPropertyRef sets field value
func (o *QueryAllocationQuantityRequirementsRequest) SetPropertyRef(v string) {
	o.PropertyRef = v
}

// GetFiscalYearRef returns the FiscalYearRef field value
func (o *QueryAllocationQuantityRequirementsRequest) GetFiscalYearRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FiscalYearRef
}

// GetFiscalYearRefOk returns a tuple with the FiscalYearRef field value
// and a boolean to check if the value has been set.
func (o *QueryAllocationQuantityRequirementsRequest) GetFiscalYearRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FiscalYearRef, true
}

// SetFiscalYearRef sets field value
func (o *QueryAllocationQuantityRequirementsRequest) SetFiscalYearRef(v string) {
	o.FiscalYearRef = v
}

func (o QueryAllocationQuantityRequirementsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryAllocationQuantityRequirementsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["property_ref"] = o.PropertyRef
	toSerialize["fiscal_year_ref"] = o.FiscalYearRef
	return toSerialize, nil
}

func (o *QueryAllocationQuantityRequirementsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"property_ref",
		"fiscal_year_ref",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryAllocationQuantityRequirementsRequest := _QueryAllocationQuantityRequirementsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryAllocationQuantityRequirementsRequest)

	if err != nil {
		return err
	}

	*o = QueryAllocationQuantityRequirementsRequest(varQueryAllocationQuantityRequirementsRequest)

	return err
}

type NullableQueryAllocationQuantityRequirementsRequest struct {
	value *QueryAllocationQuantityRequirementsRequest
	isSet bool
}

func (v NullableQueryAllocationQuantityRequirementsRequest) Get() *QueryAllocationQuantityRequirementsRequest {
	return v.value
}

func (v *NullableQueryAllocationQuantityRequirementsRequest) Set(val *QueryAllocationQuantityRequirementsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryAllocationQuantityRequirementsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryAllocationQuantityRequirementsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryAllocationQuantityRequirementsRequest(val *QueryAllocationQuantityRequirementsRequest) *NullableQueryAllocationQuantityRequirementsRequest {
	return &NullableQueryAllocationQuantityRequirementsRequest{value: val, isSet: true}
}

func (v NullableQueryAllocationQuantityRequirementsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryAllocationQuantityRequirementsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
