/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// GetSummaryResponse Contains a summary of the account
type GetSummaryResponse struct {
	// The total number of properties
	TotalProperties *int64 `json:"total_properties,omitempty"`
	// The total number of tenants
	TotalTenants *int64 `json:"total_tenants,omitempty"`
	// The total number of tenancies
	TotalTenancies *int64 `json:"total_tenancies,omitempty"`
	// The total number of cases
	TotalCases *int64 `json:"total_cases,omitempty"`
	// The total number of service providers
	TotalServiceProviders *int64 `json:"total_service_providers,omitempty"`
	// The total number of document generation flows that were not archived
	ActiveDocumentGenerationFlows *int64 `json:"active_document_generation_flows,omitempty"`
}

// NewGetSummaryResponse instantiates a new GetSummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSummaryResponse() *GetSummaryResponse {
	this := GetSummaryResponse{}
	return &this
}

// NewGetSummaryResponseWithDefaults instantiates a new GetSummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSummaryResponseWithDefaults() *GetSummaryResponse {
	this := GetSummaryResponse{}
	return &this
}

// GetTotalProperties returns the TotalProperties field value if set, zero value otherwise.
func (o *GetSummaryResponse) GetTotalProperties() int64 {
	if o == nil || o.TotalProperties == nil {
		var ret int64
		return ret
	}
	return *o.TotalProperties
}

// GetTotalPropertiesOk returns a tuple with the TotalProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSummaryResponse) GetTotalPropertiesOk() (*int64, bool) {
	if o == nil || o.TotalProperties == nil {
		return nil, false
	}
	return o.TotalProperties, true
}

// HasTotalProperties returns a boolean if a field has been set.
func (o *GetSummaryResponse) HasTotalProperties() bool {
	if o != nil && o.TotalProperties != nil {
		return true
	}

	return false
}

// SetTotalProperties gets a reference to the given int64 and assigns it to the TotalProperties field.
func (o *GetSummaryResponse) SetTotalProperties(v int64) {
	o.TotalProperties = &v
}

// GetTotalTenants returns the TotalTenants field value if set, zero value otherwise.
func (o *GetSummaryResponse) GetTotalTenants() int64 {
	if o == nil || o.TotalTenants == nil {
		var ret int64
		return ret
	}
	return *o.TotalTenants
}

// GetTotalTenantsOk returns a tuple with the TotalTenants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSummaryResponse) GetTotalTenantsOk() (*int64, bool) {
	if o == nil || o.TotalTenants == nil {
		return nil, false
	}
	return o.TotalTenants, true
}

// HasTotalTenants returns a boolean if a field has been set.
func (o *GetSummaryResponse) HasTotalTenants() bool {
	if o != nil && o.TotalTenants != nil {
		return true
	}

	return false
}

// SetTotalTenants gets a reference to the given int64 and assigns it to the TotalTenants field.
func (o *GetSummaryResponse) SetTotalTenants(v int64) {
	o.TotalTenants = &v
}

// GetTotalTenancies returns the TotalTenancies field value if set, zero value otherwise.
func (o *GetSummaryResponse) GetTotalTenancies() int64 {
	if o == nil || o.TotalTenancies == nil {
		var ret int64
		return ret
	}
	return *o.TotalTenancies
}

// GetTotalTenanciesOk returns a tuple with the TotalTenancies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSummaryResponse) GetTotalTenanciesOk() (*int64, bool) {
	if o == nil || o.TotalTenancies == nil {
		return nil, false
	}
	return o.TotalTenancies, true
}

// HasTotalTenancies returns a boolean if a field has been set.
func (o *GetSummaryResponse) HasTotalTenancies() bool {
	if o != nil && o.TotalTenancies != nil {
		return true
	}

	return false
}

// SetTotalTenancies gets a reference to the given int64 and assigns it to the TotalTenancies field.
func (o *GetSummaryResponse) SetTotalTenancies(v int64) {
	o.TotalTenancies = &v
}

// GetTotalCases returns the TotalCases field value if set, zero value otherwise.
func (o *GetSummaryResponse) GetTotalCases() int64 {
	if o == nil || o.TotalCases == nil {
		var ret int64
		return ret
	}
	return *o.TotalCases
}

// GetTotalCasesOk returns a tuple with the TotalCases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSummaryResponse) GetTotalCasesOk() (*int64, bool) {
	if o == nil || o.TotalCases == nil {
		return nil, false
	}
	return o.TotalCases, true
}

// HasTotalCases returns a boolean if a field has been set.
func (o *GetSummaryResponse) HasTotalCases() bool {
	if o != nil && o.TotalCases != nil {
		return true
	}

	return false
}

// SetTotalCases gets a reference to the given int64 and assigns it to the TotalCases field.
func (o *GetSummaryResponse) SetTotalCases(v int64) {
	o.TotalCases = &v
}

// GetTotalServiceProviders returns the TotalServiceProviders field value if set, zero value otherwise.
func (o *GetSummaryResponse) GetTotalServiceProviders() int64 {
	if o == nil || o.TotalServiceProviders == nil {
		var ret int64
		return ret
	}
	return *o.TotalServiceProviders
}

// GetTotalServiceProvidersOk returns a tuple with the TotalServiceProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSummaryResponse) GetTotalServiceProvidersOk() (*int64, bool) {
	if o == nil || o.TotalServiceProviders == nil {
		return nil, false
	}
	return o.TotalServiceProviders, true
}

// HasTotalServiceProviders returns a boolean if a field has been set.
func (o *GetSummaryResponse) HasTotalServiceProviders() bool {
	if o != nil && o.TotalServiceProviders != nil {
		return true
	}

	return false
}

// SetTotalServiceProviders gets a reference to the given int64 and assigns it to the TotalServiceProviders field.
func (o *GetSummaryResponse) SetTotalServiceProviders(v int64) {
	o.TotalServiceProviders = &v
}

// GetActiveDocumentGenerationFlows returns the ActiveDocumentGenerationFlows field value if set, zero value otherwise.
func (o *GetSummaryResponse) GetActiveDocumentGenerationFlows() int64 {
	if o == nil || o.ActiveDocumentGenerationFlows == nil {
		var ret int64
		return ret
	}
	return *o.ActiveDocumentGenerationFlows
}

// GetActiveDocumentGenerationFlowsOk returns a tuple with the ActiveDocumentGenerationFlows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSummaryResponse) GetActiveDocumentGenerationFlowsOk() (*int64, bool) {
	if o == nil || o.ActiveDocumentGenerationFlows == nil {
		return nil, false
	}
	return o.ActiveDocumentGenerationFlows, true
}

// HasActiveDocumentGenerationFlows returns a boolean if a field has been set.
func (o *GetSummaryResponse) HasActiveDocumentGenerationFlows() bool {
	if o != nil && o.ActiveDocumentGenerationFlows != nil {
		return true
	}

	return false
}

// SetActiveDocumentGenerationFlows gets a reference to the given int64 and assigns it to the ActiveDocumentGenerationFlows field.
func (o *GetSummaryResponse) SetActiveDocumentGenerationFlows(v int64) {
	o.ActiveDocumentGenerationFlows = &v
}

func (o GetSummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TotalProperties != nil {
		toSerialize["total_properties"] = o.TotalProperties
	}
	if o.TotalTenants != nil {
		toSerialize["total_tenants"] = o.TotalTenants
	}
	if o.TotalTenancies != nil {
		toSerialize["total_tenancies"] = o.TotalTenancies
	}
	if o.TotalCases != nil {
		toSerialize["total_cases"] = o.TotalCases
	}
	if o.TotalServiceProviders != nil {
		toSerialize["total_service_providers"] = o.TotalServiceProviders
	}
	if o.ActiveDocumentGenerationFlows != nil {
		toSerialize["active_document_generation_flows"] = o.ActiveDocumentGenerationFlows
	}
	return json.Marshal(toSerialize)
}

type NullableGetSummaryResponse struct {
	value *GetSummaryResponse
	isSet bool
}

func (v NullableGetSummaryResponse) Get() *GetSummaryResponse {
	return v.value
}

func (v *NullableGetSummaryResponse) Set(val *GetSummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSummaryResponse(val *GetSummaryResponse) *NullableGetSummaryResponse {
	return &NullableGetSummaryResponse{value: val, isSet: true}
}

func (v NullableGetSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
