/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Attachment1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Attachment1{}

// Attachment1 struct for Attachment1
type Attachment1 struct {
	Filename string `json:"filename"`
	// Base64-encoded file content
	Content string `json:"content"`
}

type _Attachment1 Attachment1

// NewAttachment1 instantiates a new Attachment1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachment1(filename string, content string) *Attachment1 {
	this := Attachment1{}
	this.Filename = filename
	this.Content = content
	return &this
}

// NewAttachment1WithDefaults instantiates a new Attachment1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachment1WithDefaults() *Attachment1 {
	this := Attachment1{}
	return &this
}

// GetFilename returns the Filename field value
func (o *Attachment1) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *Attachment1) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *Attachment1) SetFilename(v string) {
	o.Filename = v
}

// GetContent returns the Content field value
func (o *Attachment1) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *Attachment1) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *Attachment1) SetContent(v string) {
	o.Content = v
}

func (o Attachment1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Attachment1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filename"] = o.Filename
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *Attachment1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filename",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttachment1 := _Attachment1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttachment1)

	if err != nil {
		return err
	}

	*o = Attachment1(varAttachment1)

	return err
}

type NullableAttachment1 struct {
	value *Attachment1
	isSet bool
}

func (v NullableAttachment1) Get() *Attachment1 {
	return v.value
}

func (v *NullableAttachment1) Set(val *Attachment1) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachment1) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachment1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachment1(val *Attachment1) *NullableAttachment1 {
	return &NullableAttachment1{value: val, isSet: true}
}

func (v NullableAttachment1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachment1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
