/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the QueryInvoicesV2Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryInvoicesV2Response{}

// QueryInvoicesV2Response The response to a query invoice request
type QueryInvoicesV2Response struct {
	Invoices []Invoice `json:"invoices,omitempty"`
	// total number of invoices matching the query, ignoring limit and offset
	TotalCount *int64 `json:"total_count,omitempty"`
	// number of invoices that were skipped in the result
	Offset *int32 `json:"offset,omitempty"`
}

// NewQueryInvoicesV2Response instantiates a new QueryInvoicesV2Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryInvoicesV2Response() *QueryInvoicesV2Response {
	this := QueryInvoicesV2Response{}
	return &this
}

// NewQueryInvoicesV2ResponseWithDefaults instantiates a new QueryInvoicesV2Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryInvoicesV2ResponseWithDefaults() *QueryInvoicesV2Response {
	this := QueryInvoicesV2Response{}
	return &this
}

// GetInvoices returns the Invoices field value if set, zero value otherwise.
func (o *QueryInvoicesV2Response) GetInvoices() []Invoice {
	if o == nil || IsNil(o.Invoices) {
		var ret []Invoice
		return ret
	}
	return o.Invoices
}

// GetInvoicesOk returns a tuple with the Invoices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryInvoicesV2Response) GetInvoicesOk() ([]Invoice, bool) {
	if o == nil || IsNil(o.Invoices) {
		return nil, false
	}
	return o.Invoices, true
}

// HasInvoices returns a boolean if a field has been set.
func (o *QueryInvoicesV2Response) HasInvoices() bool {
	if o != nil && !IsNil(o.Invoices) {
		return true
	}

	return false
}

// SetInvoices gets a reference to the given []Invoice and assigns it to the Invoices field.
func (o *QueryInvoicesV2Response) SetInvoices(v []Invoice) {
	o.Invoices = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *QueryInvoicesV2Response) GetTotalCount() int64 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int64
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryInvoicesV2Response) GetTotalCountOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *QueryInvoicesV2Response) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int64 and assigns it to the TotalCount field.
func (o *QueryInvoicesV2Response) SetTotalCount(v int64) {
	o.TotalCount = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *QueryInvoicesV2Response) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryInvoicesV2Response) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *QueryInvoicesV2Response) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *QueryInvoicesV2Response) SetOffset(v int32) {
	o.Offset = &v
}

func (o QueryInvoicesV2Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryInvoicesV2Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Invoices) {
		toSerialize["invoices"] = o.Invoices
	}
	if !IsNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	return toSerialize, nil
}

type NullableQueryInvoicesV2Response struct {
	value *QueryInvoicesV2Response
	isSet bool
}

func (v NullableQueryInvoicesV2Response) Get() *QueryInvoicesV2Response {
	return v.value
}

func (v *NullableQueryInvoicesV2Response) Set(val *QueryInvoicesV2Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryInvoicesV2Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryInvoicesV2Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryInvoicesV2Response(val *QueryInvoicesV2Response) *NullableQueryInvoicesV2Response {
	return &NullableQueryInvoicesV2Response{value: val, isSet: true}
}

func (v NullableQueryInvoicesV2Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryInvoicesV2Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
