/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkflowInitStepExecutionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowInitStepExecutionRequest{}

// WorkflowInitStepExecutionRequest a request containing the data for executing the init step of a workflow execution
type WorkflowInitStepExecutionRequest struct {
	// the ID of the action that was executed on the step
	Action string `json:"action"`
	// the data to be used for executing the workflow step
	Data map[string]interface{} `json:"data,omitempty"`
}

type _WorkflowInitStepExecutionRequest WorkflowInitStepExecutionRequest

// NewWorkflowInitStepExecutionRequest instantiates a new WorkflowInitStepExecutionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowInitStepExecutionRequest(action string) *WorkflowInitStepExecutionRequest {
	this := WorkflowInitStepExecutionRequest{}
	this.Action = action
	return &this
}

// NewWorkflowInitStepExecutionRequestWithDefaults instantiates a new WorkflowInitStepExecutionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowInitStepExecutionRequestWithDefaults() *WorkflowInitStepExecutionRequest {
	this := WorkflowInitStepExecutionRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *WorkflowInitStepExecutionRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepExecutionRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *WorkflowInitStepExecutionRequest) SetAction(v string) {
	o.Action = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *WorkflowInitStepExecutionRequest) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowInitStepExecutionRequest) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *WorkflowInitStepExecutionRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *WorkflowInitStepExecutionRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o WorkflowInitStepExecutionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowInitStepExecutionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *WorkflowInitStepExecutionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowInitStepExecutionRequest := _WorkflowInitStepExecutionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowInitStepExecutionRequest)

	if err != nil {
		return err
	}

	*o = WorkflowInitStepExecutionRequest(varWorkflowInitStepExecutionRequest)

	return err
}

type NullableWorkflowInitStepExecutionRequest struct {
	value *WorkflowInitStepExecutionRequest
	isSet bool
}

func (v NullableWorkflowInitStepExecutionRequest) Get() *WorkflowInitStepExecutionRequest {
	return v.value
}

func (v *NullableWorkflowInitStepExecutionRequest) Set(val *WorkflowInitStepExecutionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowInitStepExecutionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowInitStepExecutionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowInitStepExecutionRequest(val *WorkflowInitStepExecutionRequest) *NullableWorkflowInitStepExecutionRequest {
	return &NullableWorkflowInitStepExecutionRequest{value: val, isSet: true}
}

func (v NullableWorkflowInitStepExecutionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowInitStepExecutionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
