/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the CreateOrUpdateCustomFormRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdateCustomFormRequest{}

// CreateOrUpdateCustomFormRequest The data required to create a new custom form
type CreateOrUpdateCustomFormRequest struct {
	// the name of the form
	Name *string `json:"name,omitempty"`
	// the description of the form
	Description    *string            `json:"description,omitempty"`
	FormDefinition NullableCustomForm `json:"form_definition,omitempty"`
	Version        *int32             `json:"version,omitempty"`
}

// NewCreateOrUpdateCustomFormRequest instantiates a new CreateOrUpdateCustomFormRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateCustomFormRequest() *CreateOrUpdateCustomFormRequest {
	this := CreateOrUpdateCustomFormRequest{}
	return &this
}

// NewCreateOrUpdateCustomFormRequestWithDefaults instantiates a new CreateOrUpdateCustomFormRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateCustomFormRequestWithDefaults() *CreateOrUpdateCustomFormRequest {
	this := CreateOrUpdateCustomFormRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateOrUpdateCustomFormRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateCustomFormRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateOrUpdateCustomFormRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateOrUpdateCustomFormRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateOrUpdateCustomFormRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateCustomFormRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateOrUpdateCustomFormRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateOrUpdateCustomFormRequest) SetDescription(v string) {
	o.Description = &v
}

// GetFormDefinition returns the FormDefinition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateCustomFormRequest) GetFormDefinition() CustomForm {
	if o == nil || IsNil(o.FormDefinition.Get()) {
		var ret CustomForm
		return ret
	}
	return *o.FormDefinition.Get()
}

// GetFormDefinitionOk returns a tuple with the FormDefinition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateCustomFormRequest) GetFormDefinitionOk() (*CustomForm, bool) {
	if o == nil {
		return nil, false
	}
	return o.FormDefinition.Get(), o.FormDefinition.IsSet()
}

// HasFormDefinition returns a boolean if a field has been set.
func (o *CreateOrUpdateCustomFormRequest) HasFormDefinition() bool {
	if o != nil && o.FormDefinition.IsSet() {
		return true
	}

	return false
}

// SetFormDefinition gets a reference to the given NullableCustomForm and assigns it to the FormDefinition field.
func (o *CreateOrUpdateCustomFormRequest) SetFormDefinition(v CustomForm) {
	o.FormDefinition.Set(&v)
}

// SetFormDefinitionNil sets the value for FormDefinition to be an explicit nil
func (o *CreateOrUpdateCustomFormRequest) SetFormDefinitionNil() {
	o.FormDefinition.Set(nil)
}

// UnsetFormDefinition ensures that no value is present for FormDefinition, not even an explicit nil
func (o *CreateOrUpdateCustomFormRequest) UnsetFormDefinition() {
	o.FormDefinition.Unset()
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CreateOrUpdateCustomFormRequest) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateCustomFormRequest) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CreateOrUpdateCustomFormRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *CreateOrUpdateCustomFormRequest) SetVersion(v int32) {
	o.Version = &v
}

func (o CreateOrUpdateCustomFormRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdateCustomFormRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.FormDefinition.IsSet() {
		toSerialize["form_definition"] = o.FormDefinition.Get()
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableCreateOrUpdateCustomFormRequest struct {
	value *CreateOrUpdateCustomFormRequest
	isSet bool
}

func (v NullableCreateOrUpdateCustomFormRequest) Get() *CreateOrUpdateCustomFormRequest {
	return v.value
}

func (v *NullableCreateOrUpdateCustomFormRequest) Set(val *CreateOrUpdateCustomFormRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateCustomFormRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateCustomFormRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateCustomFormRequest(val *CreateOrUpdateCustomFormRequest) *NullableCreateOrUpdateCustomFormRequest {
	return &NullableCreateOrUpdateCustomFormRequest{value: val, isSet: true}
}

func (v NullableCreateOrUpdateCustomFormRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateCustomFormRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
