/*
Udoma

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InventoryItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryItem{}

// InventoryItem An inventory item belonging to a property, such as a bed, couch, TV, etc.
type InventoryItem struct {
	// Unique and immutable ID attribute of the entity that is generated when the instance is created. The ID is unique within the system accross all accounts and it can be used to reference the entity in other entities or to retrieve it from the backend.
	Id string `json:"id"`
	// The date and time the entity was created
	CreatedAt int64 `json:"created_at"`
	// The date and time the entity was last updated
	UpdatedAt int64 `json:"updated_at"`
	// The name of the inventory item (e.g. 'Bed', 'Couch', 'TV').
	Name string `json:"name"`
	// Optional description providing more details about the inventory item.
	Description *string `json:"description,omitempty"`
	// The room where the inventory item is located (e.g. 'Living room', 'Bedroom').
	Room *string `json:"room,omitempty"`
	// The quantity of this inventory item in the room or property.
	Quantity *int32 `json:"quantity,omitempty"`
	// Serial number of the inventory item, if available.
	SerialNumber *string                `json:"serial_number,omitempty"`
	Condition    InventoryConditionEnum `json:"condition"`
	// List of IDs of attachments (typically images) that are associated with this inventory item.
	AttachmentRefs []string `json:"attachment_refs,omitempty"`
	// Extensions data for this inventory item, keyed by extension key
	Extensions *map[string]map[string]interface{} `json:"extensions,omitempty"`
	// The ID of the property this inventory item belongs to.
	PropertyRef string `json:"property_ref"`
}

type _InventoryItem InventoryItem

// NewInventoryItem instantiates a new InventoryItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryItem(id string, createdAt int64, updatedAt int64, name string, condition InventoryConditionEnum, propertyRef string) *InventoryItem {
	this := InventoryItem{}
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Name = name
	this.Condition = condition
	this.PropertyRef = propertyRef
	return &this
}

// NewInventoryItemWithDefaults instantiates a new InventoryItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryItemWithDefaults() *InventoryItem {
	this := InventoryItem{}
	return &this
}

// GetId returns the Id field value
func (o *InventoryItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InventoryItem) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *InventoryItem) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *InventoryItem) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *InventoryItem) GetUpdatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetUpdatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *InventoryItem) SetUpdatedAt(v int64) {
	o.UpdatedAt = v
}

// GetName returns the Name field value
func (o *InventoryItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InventoryItem) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InventoryItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InventoryItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InventoryItem) SetDescription(v string) {
	o.Description = &v
}

// GetRoom returns the Room field value if set, zero value otherwise.
func (o *InventoryItem) GetRoom() string {
	if o == nil || IsNil(o.Room) {
		var ret string
		return ret
	}
	return *o.Room
}

// GetRoomOk returns a tuple with the Room field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetRoomOk() (*string, bool) {
	if o == nil || IsNil(o.Room) {
		return nil, false
	}
	return o.Room, true
}

// HasRoom returns a boolean if a field has been set.
func (o *InventoryItem) HasRoom() bool {
	if o != nil && !IsNil(o.Room) {
		return true
	}

	return false
}

// SetRoom gets a reference to the given string and assigns it to the Room field.
func (o *InventoryItem) SetRoom(v string) {
	o.Room = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *InventoryItem) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *InventoryItem) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *InventoryItem) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *InventoryItem) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *InventoryItem) HasSerialNumber() bool {
	if o != nil && !IsNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *InventoryItem) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetCondition returns the Condition field value
func (o *InventoryItem) GetCondition() InventoryConditionEnum {
	if o == nil {
		var ret InventoryConditionEnum
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetConditionOk() (*InventoryConditionEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *InventoryItem) SetCondition(v InventoryConditionEnum) {
	o.Condition = v
}

// GetAttachmentRefs returns the AttachmentRefs field value if set, zero value otherwise.
func (o *InventoryItem) GetAttachmentRefs() []string {
	if o == nil || IsNil(o.AttachmentRefs) {
		var ret []string
		return ret
	}
	return o.AttachmentRefs
}

// GetAttachmentRefsOk returns a tuple with the AttachmentRefs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetAttachmentRefsOk() ([]string, bool) {
	if o == nil || IsNil(o.AttachmentRefs) {
		return nil, false
	}
	return o.AttachmentRefs, true
}

// HasAttachmentRefs returns a boolean if a field has been set.
func (o *InventoryItem) HasAttachmentRefs() bool {
	if o != nil && !IsNil(o.AttachmentRefs) {
		return true
	}

	return false
}

// SetAttachmentRefs gets a reference to the given []string and assigns it to the AttachmentRefs field.
func (o *InventoryItem) SetAttachmentRefs(v []string) {
	o.AttachmentRefs = v
}

// GetExtensions returns the Extensions field value if set, zero value otherwise.
func (o *InventoryItem) GetExtensions() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Extensions) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return *o.Extensions
}

// GetExtensionsOk returns a tuple with the Extensions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetExtensionsOk() (*map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Extensions) {
		return nil, false
	}
	return o.Extensions, true
}

// HasExtensions returns a boolean if a field has been set.
func (o *InventoryItem) HasExtensions() bool {
	if o != nil && !IsNil(o.Extensions) {
		return true
	}

	return false
}

// SetExtensions gets a reference to the given map[string]map[string]interface{} and assigns it to the Extensions field.
func (o *InventoryItem) SetExtensions(v map[string]map[string]interface{}) {
	o.Extensions = &v
}

// GetPropertyRef returns the PropertyRef field value
func (o *InventoryItem) GetPropertyRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PropertyRef
}

// GetPropertyRefOk returns a tuple with the PropertyRef field value
// and a boolean to check if the value has been set.
func (o *InventoryItem) GetPropertyRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PropertyRef, true
}

// SetPropertyRef sets field value
func (o *InventoryItem) SetPropertyRef(v string) {
	o.PropertyRef = v
}

func (o InventoryItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Room) {
		toSerialize["room"] = o.Room
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.SerialNumber) {
		toSerialize["serial_number"] = o.SerialNumber
	}
	toSerialize["condition"] = o.Condition
	if !IsNil(o.AttachmentRefs) {
		toSerialize["attachment_refs"] = o.AttachmentRefs
	}
	if !IsNil(o.Extensions) {
		toSerialize["extensions"] = o.Extensions
	}
	toSerialize["property_ref"] = o.PropertyRef
	return toSerialize, nil
}

func (o *InventoryItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_at",
		"updated_at",
		"name",
		"condition",
		"property_ref",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInventoryItem := _InventoryItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInventoryItem)

	if err != nil {
		return err
	}

	*o = InventoryItem(varInventoryItem)

	return err
}

type NullableInventoryItem struct {
	value *InventoryItem
	isSet bool
}

func (v NullableInventoryItem) Get() *InventoryItem {
	return v.value
}

func (v *NullableInventoryItem) Set(val *InventoryItem) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryItem) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryItem(val *InventoryItem) *NullableInventoryItem {
	return &NullableInventoryItem{value: val, isSet: true}
}

func (v NullableInventoryItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
