name: Terraform Provider Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Create .env file
        run: |
          echo "UDOMA_ENDPOINT=http://test.udoma.co" >> .env
          echo "UDOMA_API_KEY=${{ secrets.API_KEY }} " >> .env
          echo "UDOMA_KEY_SECRET=${{ secrets.KEY_SECRET }}" >> .env


      - name: Run tests
        run: TF_ACC=1 go test ./...
